### ISSUE TITLE
Docs:

### ISSUE THREAD

**Issue by rnpridgeon** [confluentinc/cp-docker-images#106]
Quickstart;Introduction: 

> It is also worth noting that we will be configuring Kafka and Zookeeper to store data locally in the Docker containers. However, you can also refer to our bla bla bla for an example of how to add mounted volumes to the host machine to persist data in the event that the container stops running. This is important when running a system like Kafka on Docker, as it relies heavily on the filesystem for storing and caching messages.It

I imagine bla bla blah was meant to be something more descriptive

**Comment by samjhecht** [comment]
no longer an issue
