### ISSUE TITLE
Docs:Quickstart

### ISSUE THREAD

**Issue by rnpridgeon** [confluentinc/cp-docker-images#107]
tagging issue: 

docker run -d \
    --net=host \
    --name=zookeeper \
    -e ZOOKEEPER_CLIENT_PORT=32181 \
    -e ZOOKEEPER_TICK_TIME=2000 \
    confluentinc/cp-zookeeper:3.0.1

docker: Tag 3.0.1 not found in repository docker.io/confluentinc/cp-zookeeper.

**Comment by samjhecht** [comment]
This is no longer an issue
