### ISSUE TITLE
Docs:Quickstart - link 

### ISSUE THREAD

**Issue by rnpridgeon** [confluentinc/cp-docker-images#108]
>  this command, we tell Docker to run the confluentinc/cp-zookeeper:3.0.1 container named zookeeper. We also specify that we want to use host networking and pass in the two required parameters for running Zookeeper: ZOOKEEPER_CLIENT_PORT and ZOOKEEPER_TICK_TIME. For a full list of the available configuration options and more details on passing environment variables into Docker containers, go to this link that is yet to be created.

I imagine "go to this link that is yet to be created." should be something else

**Comment by samjhecht** [comment]
fixed.
