### ISSUE TITLE
A few typos in the 'connect-avro-jdbc' tutorial that may be worth fixing

### ISSUE THREAD

**Issue by Analect** [confluentinc/cp-docker-images#140]
I worked through this tutorial, which is very helpful.  Thanks.

There's a few minor typos in some of the commands that might need tweaking, so others don't easily stumble.

In the section 'Create the JDBC Source connector', about three-quarters the way through, the POST to the Kafka Connect API is against port 28082, instead of 28083 ... and it is using a prefix of 'quickstart-jdbc-foo' without a trailing dash ... whereas your response underneath suggests that the prefix should have been just 'quickstart-jdbc-'.

Anyway, this results in a topic for the data getting generated as 'quickstart-jdbc-footest' ... 

Also, you've ended up creating the 'connector' as 'quickstart-jdbc-source-foo' , so the 'status' call to the API lower down using name 'quickstart-jdbc-source' is failing.

Running the 'kafka-avro-console-consumer' call lower down again needed to reference the topic as 'quickstart-jdbc-footest' for it to work.

Obviously all this is easily fixed by amending the the first prefix back to 'quickstart-jdbc-' and leaving out the '-foo' from the end of the connector name.

It's also not clear from the tutorial why you created the topic 'quickstart-avro-data' further up ... since I don't think you ended up using it ... or did I miss something?

**Comment by samjhecht** [comment]
Hi @Analect - Thanks for catching all of this.  I'm pushing a fix now that will clean all this up.

**Comment by Analect** [comment]
No problem.
