### ISSUE TITLE
Schema registry config checker too strict on schema registry url

### ISSUE THREAD

**Issue by ecesena** [confluentinc/cp-docker-images#147]
This check doesn't look correct to me:
https://github.com/confluentinc/cp-docker-images/blob/master/debian/kafka-connect/include/etc/confluent/docker/configure#L47

If keys are avro encoded, then you need the schema registry url for keys.
If values are avro encoded, then you need the schema registry url for values.

You can have, for instance, String keys and Avro-encoded values.

**Comment by arrawatia** [comment]
Thanks for reporting this. I will update the code to check for keys and value separately.

Just curious, are you using different convertors for keys and values ?

**Comment by ecesena** [comment]
Typically avro schemas only for values (keys are just strings). Given your experience, is this uncommon?

**Comment by ewencp** [comment]
@ecesena That's the type of case we'd expect as an exception. It's not necessarily unusual, but can be difficult to standardize on if you allow any other primitive type as a key, e.g. longs for user IDs or something like that. Also, connectors may or may not handle the primitive type you've standardized on. Kafka Connect in 0.10.1 will support per-connector converter settings which can help with these challenges. Of course, if you're fine always using strings and all the connectors you use can handle it, then no problem!
