### ISSUE TITLE
Kafka-ready blocks security enablement for Schema Registry Image

### ISSUE THREAD

**Issue by samjhecht** [confluentinc/cp-docker-images#176]
Security support was added to SR in 3.0.1, but SR's cub kafka-ready check currently restricts enablement of security for SR w/ secure kafka. 

kafka-ready currently supports 2 options:
1. get broker list from ZK (for legacy reasons related to SR & RP)
2. you give the broker list and security config

Given that Schema Registry now supports secure clusters and has a bootstrap.list, we'll need to switch to using the second option.  

we can do the following: 
- remove this blocker for SR much as we do for Control Center by replacing: https://github.com/confluentinc/cp-docker-images/blob/master/debian/schema-registry/include/etc/confluent/docker/ensure#L26
- with: https://github.com/confluentinc/cp-docker-images/blob/master/debian/enterprise-control-center/include/etc/confluent/docker/ensure#L27-L30

We'll need to add the following:
```
cub kafka-ready 1 \
  "${SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT:-40}" \
  -b "${SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS}" \
  --config /etc/"${COMPONENT}"/admin.properties
```

and we'll need to add an admin properties file for SR like this one: https://github.com/confluentinc/cp-docker-images/blob/master/debian/enterprise-control-center/include/etc/confluent/docker/admin.properties.template

```
{% set security_props = env_to_props('SCHEMA_REGISTRY_KAFKASTORE', '') -%}
{% for name, value in security_props.iteritems() -%}
{{name}}={{value}}
{% endfor -%}
```

Then we need to add a like like this @ the configure script: https://github.com/confluentinc/cp-docker-images/blob/master/debian/enterprise-control-center/include/etc/confluent/docker/configure#L36

Finally, we need tests!

**Comment by sophieqianCA** [comment]
Hi, @samjhecht :  I build the docker image with the change suggested by you,  got following error:
admin.properties file not been generated from template.

echo "===> Check if Kafka is healthy ..."
===> Check if Kafka is healthy ...

cub kafka-ready 1 \
  "${SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT:-40}" \
  -b "${SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS}" \
  --config /etc/"${COMPONENT}"/admin.properties
+ cub kafka-ready 1 40 -b SSL://15.214.156.82:9093 --config /etc/schema-registry/admin.properties
Error while running kafka-ready.
java.io.FileNotFoundException: **/etc/schema-registry/admin.properties (No such file or directory)**
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.apache.kafka.common.utils.Utils.loadProps(Utils.java:446)
        at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:103)


The change I made in:

./debian/schema-registry/include/etc/confluent/docker/ensure
--- commented out following section--------
echo "===> Check if Kafka is healthy ..."
#cub kafka-ready \
.....

--------Add following section ---------
cub kafka-ready 1 \
  "${SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT:-40}" \
  -b "${SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS}" \
  --config /etc/"${COMPONENT}"/admin.properties


./debian/enterprise-control-center/include/etc/confluent/docker/admin.properties.template
---Add following section ----
{% set security_props = env_to_props('SCHEMA_REGISTRY_KAFKASTORE', '') -%}
{% for name, value in security_props.iteritems() -%}
{{name}}={{value}}
{% endfor -%}

Is there some change still missing?  Thanks

**Comment by sophieqianCA** [comment]
OK, just saw the last change,  I need to add sth like

dub template "/etc/confluent/docker/admin.properties.template" "${SCHEMA_REGISTRY_CONFIG_DIR}/admin.properties"

will try it now.

**Comment by sophieqianCA** [comment]
Still failed after I added

dub template "/etc/confluent/docker/admin.properties.template" "/etc/${COMPONENT}/admin.properties"

to ./debian/schema-registry/include/etc/confluent/docker/configure

---------Error-----

+ dub template /etc/confluent/docker/admin.properties.template /etc/schema-registry/admin.properties
/etc/confluent/docker/admin.properties.template
**Command [/usr/local/bin/dub template /etc/confluent/docker/admin.properties.template /etc/schema-registry/admin.properties] FAILED !**

**Comment by arrawatia** [comment]
I think ` /etc/confluent/docker/admin.properties.template ` is missing. To fix this, you will need to create `debian/schema-registry/include/etc/confluent/docker/admin.properties.template` with the following content: 
```
{% set security_props = env_to_props('SCHEMA_REGISTRY_KAFKASTORE', '') -%}
{% for name, value in security_props.iteritems() -%}
{{name}}={{value}}
{% endfor -%}
```

This will add the admin.properties to the schema-registry image. (The idea is to add a config file with security credentials that the `cub kafka-ready` command can use.)

I see that you added the code to `./debian/enterprise-control-center/include/etc/confluent/docker/admin.properties.template` instead. Sorry for not making it clear that you needed a new `admin.properties.template` in SR similar to the one in the control-center image.

**Comment by sophieqianCA** [comment]
@arrawatia : Thanks for the correction, I was able to bypass the issue I encountered earlier. But the fix is still not complete.  SR was able to pick up the bootstrap server, but it does not pick up the keystore/trustore info.  I'm attaching the SR startup logs and schema-registry.properties.

------
....
SCHEMA_REGISTRY_HOST_NAME=15.214.156.82
SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=SSL://15.214.156.82:9093
SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=15.214.156.82:2181
SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=SSL
SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION=/etc/schemaregistry/secrets/keystore.jks
SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD=test1234
SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD=test1234
SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION=/etc/schemaregistry/secrets/truststore.jks
SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD=test1234
SCHEMA_REGISTRY_LISTENERS=https://15.214.156.82:8085
SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION=/etc/schemaregistry/secrets/keystore.jks
SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD=test1234
SCHEMA_REGISTRY_SSL_KEY_PASSWORD=test1234
SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION=/etc/schemaregistry/secrets/truststore.jks
SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD=test1234
......

cub kafka-ready 1 \
  "${SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT:-40}" \
  -b "${SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS}" \
  --config /etc/"${COMPONENT}"/admin.properties
+ cub kafka-ready 1 40 -b SSL://15.214.156.82:9093 --config /etc/schema-registry/admin.properties
MetadataClientConfig values:
        ssl.protocol = TLS
        ssl.provider = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        sasl.kerberos.ticket.renew.window.factor = 0.8
        **ssl.keystore.location = null**
        **bootstrap.servers = [SSL://15.214.156.82:9093]**
        ssl.cipher.suites = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        ssl.truststore.type = JKS
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        security.protocol = PLAINTEXT
        ssl.keystore.type = JKS
        ssl.trustmanager.algorithm = PKIX
        **ssl.truststore.location = null
        ssl.keystore.password = null**
        ssl.keymanager.algorithm = SunX509
        sasl.mechanism = GSSAPI
        **ssl.key.password = null**
        sasl.kerberos.min.time.before.relogin = 60000
        **ssl.truststore.password = null**
        ssl.endpoint.identification.algorithm = null

-----  schema-registry.properties  has been populated with the correct env variables ----

[root@n15-214-156-h82 ~]# docker exec -it atlas_schema-registry  /bin/bash
root@n15-214-156-h82:/# cat /etc/schema-registry/schema-registry.properties
kafkastore.ssl.truststore.location=/etc/schemaregistry/secrets/truststore.jks
kafkastore.ssl.key.password=test1234
ssl.keystore.location=/etc/schemaregistry/secrets/keystore.jks
kafkastore.ssl.keystore.location=/etc/schemaregistry/secrets/keystore.jks
kafkastore.connection.url=15.214.156.82:2181
listeners=https://15.214.156.82:8085
ssl.key.password=test1234
kafkastore.bootstrap.servers=SSL://15.214.156.82:9093
kafkastore.ssl.keystore.password=test1234
ssl.truststore.location=/etc/schemaregistry/secrets/truststore.jks
ssl.keystore.password=test1234
kafkastore.ssl.truststore.password=test1234
host.name=15.214.156.82
ssl.truststore.password=test1234
kafkastore.security.protocol=SSL

Looks like only  kafkastore.bootstrap.servers  been picked up by MetadataClientConfig, not other SSL properties. Please advise on further fix.  Thanks

**Comment by sophieqianCA** [comment]
SR exited at the end when no broker found. 

-------------------
MetadataClientConfig values:
        ssl.protocol = TLS
        ssl.provider = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        sasl.kerberos.ticket.renew.window.factor = 0.8
        ssl.keystore.location = null
        bootstrap.servers = [SSL://15.214.156.82:9093]
        ssl.cipher.suites = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        ssl.truststore.type = JKS
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        security.protocol = PLAINTEXT
        ssl.keystore.type = JKS
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.keystore.password = null
        ssl.keymanager.algorithm = SunX509
        sasl.mechanism = GSSAPI
        ssl.key.password = null
        sasl.kerberos.min.time.before.relogin = 60000
        ssl.truststore.password = null
        ssl.endpoint.identification.algorithm = null

Request METADATA failed against node 15.214.156.82:9093 (id: -1 rack: null).
java.lang.NullPointerException
        at io.confluent.admin.utils.KafkaAdminClient.send(KafkaAdminClient.java:118)
        at io.confluent.admin.utils.KafkaAdminClient.sendAnyNode(KafkaAdminClient.java:102)
        at io.confluent.admin.utils.KafkaAdminClient.findAllBrokers(KafkaAdminClient.java:89)
        at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:127)
        at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:122)
**Request METADATA failed on all bootstrap brokers [15.214.156.82:9093 (id: -1 rack: null)].**
Expected 1 brokers but found only 0. Trying to query Kafka for metadata again ...
Expected 1 brokers but found only 0. Brokers found [].

**Comment by arrawatia** [comment]
I think there is a typo in the `admin.properties.template`, `SCHEMA_REGISTRY_KAFKASTORE` should have a `_` at the end. Something like this : 

```
{% set security_props = env_to_props('SCHEMA_REGISTRY_KAFKASTORE_', '') -%}
{% for name, value in security_props.iteritems() -%}
{{name}}={{value}}
{% endfor -%}
```

Similar to : https://github.com/confluentinc/cp-docker-images/blob/master/debian/enterprise-control-center/include/etc/confluent/docker/admin.properties.template#L1

Docs : https://github.com/confluentinc/cp-docker-images/blob/master/debian/base/include/dub#L43-L66

Sorry about this !

**Comment by sophieqianCA** [comment]
@arrawatia : Thanks,  it works now. Do you know when the fix  will go to official released SR docker image?   In the meantime, we will add building SR image to our build process.  Really appreciate all your time and help.

**Comment by sophieqianCA** [comment]
OK, I found another issue using non TLS mode,

cub kafka-ready 1 \
  "${SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT:-40}" \
  -b "${SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS}" \
  --config /etc/"${COMPONENT}"/admin.properties
/etc/confluent/docker/ensure: line 31: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: unbound variable

We should not need to set it for non TLS mode before, do we need to set SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS for non TLS and TLS mode now?

**Comment by arrawatia** [comment]
@sophieqianCA  You are welcome. If you are OK with doing a PR with the fixes, we can build a new set of images when the PR is merged.

**Comment by sophieqianCA** [comment]
With this change, for SR in non TLS mode, SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS is no longer optional, it needs to be set to sth like PLAINTEXT://${KAFKA_HOST_IP}:${KAFKA_PORT}.

**Comment by arrawatia** [comment]
@sophieqianCA Good catch.

You can add a condition that ensures that `SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS` is set when `kafkastore.security.protocol` is `SSL` or `kafkastore.sasl.kerberos.service.name` is set.

Something similar to : 
https://github.com/confluentinc/cp-docker-images/blob/master/debian/zookeeper/include/etc/confluent/docker/configure#L27-L33 
https://github.com/confluentinc/cp-docker-images/blob/master/debian/kafka/include/etc/confluent/docker/configure#L68

**Comment by adamstrawson** [comment]
Hi there, has any progress been made on that last issue from @sophieqianCA with non-TLS? Eager to get these fixes built into the image. If not, I'll be happy to send in a PR to get this wrapped up.

**Comment by sophieqianCA** [comment]
@adamstrawson   I'll submit the  PR today. Was busy earlier, I have the code ready, will run some test before submitting the PR.

**Comment by adamstrawson** [comment]
@sophieqianCA Amazing, thanks! 🌟

**Comment by sophieqianCA** [comment]
I submitted the PR, link as following

https://github.com/confluentinc/cp-docker-images/commit/b135913398d578d0ab296b3bf19d12672a5fada9

**Comment by sophieqianCA** [comment]
updated with PR https://github.com/confluentinc/cp-docker-images/pull/182

**Comment by javierholguera** [comment]
I've applied the changes described here and in the corresponding PRs and got beyond the health checks (which is great). However, I'm still stuck with a Schema Registry that doesn't work correctly with a "SSL-enabled" Kafka cluster (with only 1 onde).

When I run the image, it passes the "ensure" script and gets to the "launch" script, which executes up until a point where it displays a message saying something like this:
```[2016-12-12 16:32:14,215] INFO Kafka commitId : beb290796c342e22 (org.apache.kafka.common.utils.AppInfoParser)
[2016-12-12 16:32:14,443] WARN Failed to send SSL Close message  (org.apache.kafka.common.network.SslTransportLayer)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.kafka.common.network.SslTransportLayer.flush(SslTransportLayer.java:195)
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:163)
	at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:690)
	at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:47)
	at org.apache.kafka.common.network.Selector.close(Selector.java:487)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:368)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:291)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:260)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:195)
	at org.apache.kafka.clients.consumer.internals.Fetcher.getTopicMetadata(Fetcher.java:253)
	at org.apache.kafka.clients.consumer.KafkaConsumer.partitionsFor(KafkaConsumer.java:1318)
	at io.confluent.kafka.schemaregistry.storage.KafkaStoreReaderThread.<init>(KafkaStoreReaderThread.java:109)
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.init(KafkaStore.java:158)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:204)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.setupResources(SchemaRegistryRestApplication.java:55)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.setupResources(SchemaRegistryRestApplication.java:37)
	at io.confluent.rest.Application.createServer(Application.java:149)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:43)
```
I would have thought that there is a problem with the certificates. However if I download the Confluent command line tools and try to use them to produce and consume against the "ssl-enabled" Kafka, everything works fine with this configuration file:

```ssl.truststore.location=/etc/kafka/secrets/kafka_client_truststore.jks
ssl.truststore.password=confluent

ssl.keystore.location=/etc/kafka/secrets/kafka_client_keystore.jks
ssl.keystore.password=confluent
ssl.key.password=confluent

security.protocol=SSL
```
I'm using the Confluent docker images for version 3.0.1 (expect for SR, which I built my own image from all the commits in the repo).

Let me know if I can provide any more details that could help to explain what's happening.

Thanks!

**Comment by sophieqianCA** [comment]
@javierholguera You need to upgrade Confluent docker image to 3.1.1 with this patch SR ( 3.1.1-1).  3.0.1 Confluent docker image  will not work with SSL. I also  experienced the same error you encountered if I mix 3.0.1 with 3.1.1-1 SR.

**Comment by javierholguera** [comment]
@sophieqianCA thanks a lot for your answer! It's working now.

**Comment by javierholguera** [comment]
Any idea about when these changes will be available as part of a new release of the docker images?

**Comment by samjhecht** [comment]
Hi @javierholguera - new images were uploaded today which include these changes.

**Comment by javierholguera** [comment]
@samjhecht great! Thanks for letting me know.

**Comment by sophieqianCA** [comment]
@samjhecht Just want to confirm, which is official version of the build for us to pull?  Thanks. I realized it's nnot 3.1.1
