### ISSUE TITLE
Cannot bring up the confluent-zookeeper docker container

### ISSUE THREAD

**Issue by shivsantham** [confluentinc/cp-docker-images#177]
I downloaded the cp-docker-images and ran the make build-debian first to build all the images(base,kafka,zookeeper,kafka rest).
I got the following error "confluentinc/cp-base:" is not a valid repository/tag.

Step 20 : RUN echo "===> Updating debian ....."     && apt-get -qq update         && echo "===> Installing curl wget netcat python...."     && DEBIAN_FRONTEND=noninteractive apt-get install -y                 curl                 wget                 netcat                 python=${PYTHON_VERSION}     && echo "===> Installing python packages ..."      && curl -fSL 'https://bootstrap.pypa.io/get-pip.py' | python     && pip install --no-cache-dir --upgrade pip==${PYTHON_PIP_VERSION}     && pip install --no-cache-dir jinja2                                   requests         && echo "Installing Zulu OpenJDK ${ZULU_OPENJDK_VERSION}"     && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x219BD9C9     && echo "deb http://repos.azulsystems.com/debian stable  main" >> /etc/apt/sources.list.d/zulu.list     && apt-get -qq update     && apt-get -y install zulu-${ZULU_OPENJDK_VERSION}     && rm -rf /var/lib/apt/lists/*    && echo "===> Adding confluent repository...${CONFLUENT_DEB_REPO}/deb/${CONFLUENT_MAJOR_VERSION}.${CONFLUENT_MINOR_VERSION}"     && curl -L ${CONFLUENT_DEB_REPO}/deb/${CONFLUENT_MAJOR_VERSION}.${CONFLUENT_MINOR_VERSION}/archive.key | apt-key add -     && echo "deb [arch=amd64] ${CONFLUENT_DEB_REPO}/deb/${CONFLUENT_MAJOR_VERSION}.${CONFLUENT_MINOR_VERSION} stable main" >> /etc/apt/sources.list
 ---> Using cache
 ---> d8cbfb839be5
Step 21 : COPY include/dub /usr/local/bin/dub
 ---> Using cache
 ---> 01d744086c78
Step 22 : COPY include/cub /usr/local/bin/cub
 ---> Using cache
 ---> 35cdfeab5d12
Step 23 : COPY include/etc/confluent/docker /etc/confluent/docker
 ---> Using cache
 ---> 55a84be160b0
Successfully built 55a84be160b0
Error parsing reference: "confluentinc/cp-base:" is not a valid repository/tag

So i decided to build the images one by one, zookeeper and kafka. I was able to build the images and push to our internal repositry.
But when i try to bring up my zookeeper i get the following error. Any ideas what might causing this?

ssanthalingam:cp-docker-images-master i837588$ docker run -p 2181:2818 -p 2888:2888 -p 3888:3888 xhost:xport/confluentinc/cp-zookeeper
===> ENV Variables ...
COMPONENT=zookeeper
CONFLUENT_DEB_REPO=http://packages.confluent.io
CONFLUENT_DEB_VERSION=1
CONFLUENT_MAJOR_VERSION=3
CONFLUENT_MINOR_VERSION=1
CONFLUENT_PATCH_VERSION=0
CONFLUENT_VERSION=3.1.0
HOME=/root
HOSTNAME=9772c68aefe2
KAFKA_VERSION=0.10.1.0
LANG=C.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
PYTHON_PIP_VERSION=8.1.2
PYTHON_VERSION=2.7.9-1
SCALA_VERSION=2.11
SHLVL=1
ZULU_OPENJDK_VERSION=8=8.17.0.3
_=/usr/bin/env
===> User
uid=0(root) gid=0(root) groups=0(root)
===> Configuring ...

echo "===> ENV Variables ..."
+ echo '===> ENV Variables ...'
env | sort
+ env
+ sort

echo "===> User"
+ echo '===> User'
id
+ id

echo "===> Configuring ..."
+ echo '===> Configuring ...'
/etc/confluent/docker/configure
+ /etc/confluent/docker/configure

dub ensure ZOOKEEPER_CLIENT_PORT
+ dub ensure ZOOKEEPER_CLIENT_PORT
ZOOKEEPER_CLIENT_PORT is required.

**Comment by dbtucker** [comment]
The issue with your local zookeeper image is the absence of a few environment variables to pass in for configuring the service.   You can see ZOOKEEPER_CLIENT_PORT as one of them.   It's worth checking out the docker-compose examples in cp-docker-images/example/kafka-cluster for an example of all the necessary settings.'

In terms of the docker hub image, does "docker pull confluentinc/cp-base" work from your environment.   It looks to me like the image is public, but it's worth checking.

**Comment by arrawatia** [comment]
I think this line is causing the problem with the build : https://github.com/confluentinc/cp-docker-images/blob/master/Makefile#L41

We have a dependency on `git` for the build process and it only works on the cloned repo. A workaround is to change this line https://github.com/confluentinc/cp-docker-images/blob/master/Makefile#L5 to something static. For example, `COMMIT_ID := foo`.

**Comment by shivsantham** [comment]
Hi Sumit,

Thanks for the response. I was able to get the past the Make error after i
set the git commit_id to some static value, But i still get the
zookeeper_client_port not being set.

Thanks
Siva

**Comment by arrawatia** [comment]
As @dbtucker mentioned in his comment, each image has some required settings that have to be passed as docker env variables. This is documented here : http://docs.confluent.io/3.1.1/cp-docker-images/docs/configuration.html

I also highly recommend working through the quickstart to understand how the images work : http://docs.confluent.io/3.1.1/cp-docker-images/docs/quickstart.html

Hope this helps !

**Comment by shivsantham** [comment]
Hi David,

Thanks for the response, I was make to build all the docker images. So,  i
tag and push these images to our internal repository. And thanks for
pointing out the docker-compose files.. I could have tried that before..
Yes i can see all the containers up now/ Thanks a lot..

Thanks
Siva

**Comment by shivsantham** [comment]
Hi Sumit,

I tried the docker compose and it works. Thanks a lot !!!

Thanks
Siva
