### ISSUE TITLE
Confusion between KAFKA_LOG_DIRS and KAFKA_DATA_DIRS ??

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/cp-docker-images#183]
Hi,

I'm looking at the bootstrap scripts and it seems that their might be some confusion between two environment variables? The scenario is the following, if I want to set a custom `KAFKA_LOG_DIRS`, I set that variable to `/mnt/kafka-logs`. This is fine and gets picked up here: https://github.com/confluentinc/cp-docker-images/blob/master/debian/kafka/include/etc/confluent/docker/configure#L36

And then the "ensure" script runs, and checks for `KAFKA_DATA_DIRS` at https://github.com/confluentinc/cp-docker-images/blob/master/debian/kafka/include/etc/confluent/docker/ensure#L22 

Shouldn't this variable be also `KAFKA_LOG_DIRS` for consistency and actually doing the right check? I'm happy to provide a PR if that's indeed a bug. 

Cheers,
Stephane

**Comment by arrawatia** [comment]
@simplesteph Thanks for catching this. PRs are always welcome :)
