### ISSUE TITLE
Kafka Executables with the .sh extension are missing (only there without .sh)

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/cp-docker-images#186]
Hi,

I see the kafka shell scripts are located in /usr/bin. The issue is that they don't have a .sh extension, therefore I can't use administration tools such as https://github.com/linkedin/kafka-tools/ (it requires .sh extension). 

Is this something you can fix in the docker images, or something I should build on?

Regards,
Stephane

**Comment by samjhecht** [comment]
@simplesteph  - We use the debian packages and this can't be changed unfortunately.  You could extend the image and create a symlink with .sh extensions if you want to.  

For instructions on extending the images, you can refer to our documentation: http://docs.confluent.io/3.1.1/cp-docker-images/docs/development.html#extending-the-docker-images
