### ISSUE TITLE
Image setup improvements

### ISSUE THREAD

**Issue by cotedm** [confluentinc/cp-docker-images#19]
From a customer on the CP mailing list:

Stuart Wong wrote:

> We are using the images in production. The disclaimer these days is primarily since Confluent Support do not yet officially support Docker in production. Personally I'd also like to see these images improve their tagging, logging centrally to stdout out of the box, and support HTTP download of the config files.

https://confluent.slack.com/archives/engineering/p1469015817000022

@arrawatia don't know if it makes sense to do this initially, but for the future it'd be good to consider the user's request on making the images more usable out of the box.

**Comment by samjhecht** [comment]
This is complete
