### ISSUE TITLE
Docs: Insufficient details on security configuration

### ISSUE THREAD

**Issue by dbtucker** [confluentinc/cp-docker-images#190]
The security.rst file mentions that the secrets for the deployment can be loaded via a Docker mounted volume ... but there are no more specifics.   This needs a step-by-step discussion of what files are needed and how they are used.

Additionally, there is no example of deploying the images with arbitrary user-id's.

**Comment by samjhecht** [comment]
Good catch.  We need to add links to our docker-specific tutorials in this document: http://docs.confluent.io/3.1.1/cp-docker-images/docs/security/security.html.  

In the meantime, you can find this information in these tutorials:
* http://docs.confluent.io/3.1.1/cp-docker-images/docs/tutorials/clustered-deployment-sasl.html
* http://docs.confluent.io/3.1.1/cp-docker-images/docs/tutorials/clustered-deployment-ssl.html

**Comment by dbtucker** [comment]
Thanks, Sam.   The tutorials do cover the info I was looking for.
