### ISSUE TITLE
Kerberos image not found

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/cp-docker-images#195]
hi,

If I do the following:
```
15:21 $ docker pull confluentinc/cp-kerberos:latest
Error response from daemon: repository confluentinc/cp-kerberos not found: does not exist or no pull access
```

I'm getting an error. I don't see the image being published indeed. It seems to be required to run the following: 
https://github.com/confluentinc/cp-docker-images/blob/f432909b3323ff033338c6f4bec36b555f8d3caa/examples/kafka-cluster-sasl/docker-compose.yml#L62

**Comment by samjhecht** [comment]
Hi @simplesteph - Confluent does not currently provide a Kerberos image via DockerHub, so you'll need to find or build one on your own.  

That docker-compose.yml file is provided for use alongside our tutorial on Clustered Deployment with SASL that may be found in the documentation.   For the purpose of the tutorial and our testing, we do provide a Dockerfile and associated tooling to build a Kerberos image on your own.  Instructions for doing so can be found here: http://docs.confluent.io/3.1.1/cp-docker-images/docs/tutorials/clustered-deployment-sasl.html

You can find the Dockerfile here: 
https://github.com/confluentinc/cp-docker-images/blob/master/tests/images/kerberos/Dockerfile

However, if you have another Kerberos image that you wish to use, you'll need to update the docker-compose.yml file accordingly.

**Comment by pmeister** [comment]
I'm working through trying to get Kafka configured with Kerberos/SASL-based authentication and have been struggling to find up-to-date and complete documentation.  The information in this ticket has been helpful, but I'm still having trouble.

The tutorial page linked to above, titled "Clustered Deployment Using SASL and SSL", is in the 3.1.1 version of the docs, and appears to have been removed from the 5.x docs.  The latest version I've found is in 4.1.3 (https://docs.confluent.io/4.1.3/installation/docker/docs/tutorials/clustered-deployment-sasl.html).  I'm not finding anything nearly as comprehensive in the 5.x docs.  Am I just missing it?

As for the Kerberos image, I've been unable to get the Dockerfile to work.  The install process fails as follows:  

```
Error: Cannot retrieve repository metadata (repomd.xml) for repository: epel. Please verify its path and try again
The command '/bin/sh -c yum install -y krb5-server krb5-libs krb5-auth-dialog krb5-workstation' returned a non-zero code: 1
```

I suspect this failure has something to do with the age of this Dockerfile and the centos 6.6 version it uses. Perhaps the SSL root certificates are out of date.  I tried upgrading the Dockerfile to use centos7, but Kerberos is completely different in that version and none of the directories/files referenced by the config.sh script even exist.

Is there some place I can find some more up-to-date information to help get this working?

**Comment by jocelyndrean** [comment]
@pmeister This error shows that your machine couldn't connect to repository epel. To update your system, you could disable it in file /etc/yum.repos.d/epel.repo by changing enable from 1 to 0 or just run `yum update --disablerepo=epel*"

You can use this Dockerfile
```
FROM centos:6.6

ARG COMMIT_ID=unknown
LABEL io.confluent.docker.git.id=$COMMIT_ID
ARG BUILD_NUMBER=-1
LABEL io.confluent.docker.build.number=$BUILD_NUMBER
LABEL io.confluent.docker=true

# EPEL
RUN rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

RUN yum update -y --disablerepo=epel*

# fix issue "Rpmdb checksum is invalid"
RUN yum install -y yum-plugin-ovl

RUN yum install -y krb5-server krb5-libs krb5-auth-dialog krb5-workstation

EXPOSE 88 749

ADD ./config.sh /config.sh

ENTRYPOINT ["/config.sh"]

```
