### ISSUE TITLE
Docker build seems wrong for 3.1.2. Kafka hasn't been updated

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/cp-docker-images#212]
Hi

It seems the kafka version are wrong with the new images:

```
14:37 $ docker run -it confluentinc/cp-kafka:3.1.2 env | grep VERSION
PYTHON_VERSION=2.7.9-1
PYTHON_PIP_VERSION=8.1.2
SCALA_VERSION=2.11

CONFLUENT_MAJOR_VERSION=3
CONFLUENT_MINOR_VERSION=1
CONFLUENT_PATCH_VERSION=1
CONFLUENT_VERSION=3.1.1
CONFLUENT_DEB_VERSION=1
KAFKA_VERSION=0.10.1.0
ZULU_OPENJDK_VERSION=8=8.17.0.3
```

I was expecting `0.10.1.1` for `KAFKA_VERSION`

**Comment by arrawatia** [comment]
@simplesteph Thanks for reporting this. I will fix this and upload a new set of images to dockerhub soon.

**Comment by samjhecht** [comment]
@simplesteph - new versions of the images have now been deployed to dockerhub.  thanks again for reporting this issue!

**Comment by simplesteph** [comment]
you're more than welcome. Would be great to have some kind of automated testing in the future to test that out.
