### ISSUE TITLE
Kafka Connect hostname HTTPS

### ISSUE THREAD

**Issue by adamstrawson** [confluentinc/cp-docker-images#216]
I can't find any mention of this in the documenation, and setting the values has a trial as no effect so I assume this isn't supported at the moment, but I wanted to confirm if this was definitely the case.

Our entire Kafka Cluster is now SSL only, with the exception of Kafka Connect Rest. (consumer/producer communication is over SSL though).

As an example in Schema Registry I can set the below env variables to enable HTTPS

```
SCHEMA_REGISTRY_LISTENERS: "https://0.0.0.0:8081"
SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: "/dir/node.keystore.jks"
SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: "foo"
SCHEMA_REGISTRY_SSL_KEY_PASSWORD: "foo"
SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: "/dir/node.truststore.jks"
SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: "foo"
```

Or similar for Control Center
```
CONTROL_CENTER_REST_LISTENERS: "https://0.0.0.0:9021"
CONTROL_CENTER_REST_SSL_KEYSTORE_LOCATION: "/dir/node.keystore.jks"
CONTROL_CENTER_REST_SSL_KEYSTORE_PASSWORD: "foo"
CONTROL_CENTER_REST_SSL_TRUSTSTORE_LOCATION: "/dir/node.truststore.jks"
CONTROL_CENTER_REST_SSL_TRUSTSTORE_PASSWORD: "foo"
CONTROL_CENTER_REST_SSL_KEY_PASSWORD: "foo"
```

However similar variables don't work for Kafka Connect, the hostname only works as HTTP.

I have set all the usual SSL related vars already for it to work with our cluster, such as;

```
CONNECT_SSL_*
CONNECT_PRODUCER_SSL_*
CONNECT_CONSUMER_SSL_*
```

And I've tried just setting similar with Control Center with `CONNECT_REST_SSL_*`, but no luck..

Am I missing something here, or does Connect not support HTTPS on the hostname?

**Comment by ewencp** [comment]
The REST API for Connect hasn't had SSL support added yet.

**Comment by ewencp** [comment]
By the way, https://issues.apache.org/jira/browse/KAFKA-4029 is filed for this, but nobody is currently working on it.

**Comment by adamstrawson** [comment]
Thanks @ewencp - I'll see how much of an issue it is with us not running it with SSL, as it's a problem I may see about getting one of our java guys to submit a PR.
