### ISSUE TITLE
Wrong variable names in Zookeeper image? ex: KAFKA_JMX_PORT

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/cp-docker-images#218]
I'm a bit confused about the following variables:
https://github.com/confluentinc/cp-docker-images/blob/3.1.x/debian/zookeeper/include/etc/confluent/docker/configure#L40

https://github.com/confluentinc/cp-docker-images/blob/3.1.x/debian/zookeeper/include/etc/confluent/docker/launch#L30

Are those expected to be named KAFKA_ ? I'm not sure where they tie down the road, but I believe they should be ZOOKEEPER_ ?

**Comment by jomach** [comment]
I think this was a copy paste error... But yeah it could be fixed.

**Comment by kwilcox** [comment]
Keep in mind that some people (this guy) have come to rely on that copy and paste error!

**Comment by arrawatia** [comment]
Actually, this is not a copy-paste error. Zookeeper start script assumes these variables to be called KAFKA_JMX_* as it uses `kafka-run-class` script which sets up JMX. So, I kept the names the same to avoid confusion (which it clearly failed to do :) ).

**Comment by simplesteph** [comment]
@arrawatia Interesting. I think the confusing part is {COMPONENT}_VAR_NAME => var.name as a property was an accepted behaviour for me, so whenever I see KAFKA_ in the zookeeper image for example I think there's a typo. Makes sense though, will close this for now
