### ISSUE TITLE
Kafka Connect new connector plugin not being loaded

### ISSUE THREAD

**Issue by adamstrawson** [confluentinc/cp-docker-images#219]
According to the documentation, to install a new connector plugin into Kafka Connect, you mount a volume to the container called `/etc/kafka-connect/jars` and add your jar files into that directory.

I've set up the volume, added the jar, and deployed the container, but it's not showing up as a connector plugin, and nothing of any use in the logs.

I'm doing a `GET` to `http://kafka-connect:8083/connector-plugins` to return which connector-plugins are available, all the defaults are there, but not the plugin I've added to `/etc/kafka-connect/jars`

I should expect to see `com.spredfast.kafka.connect.s3.sink.S3SinkConnector` (https://mvnrepository.com/artifact/com.spredfast.kafka.connect.s3/kafka-connect-s3/0.3.4) 

Anything I'm doing wrong here, or steps to help troubleshoot?

**Comment by treziac** [comment]
You need to take the shadowed jar which contains the dependencies
You can build it yourself by cloning the spredfast github repo and run `gradlew shadowJar`
Copy it in the repository as previously and it will work

But it's right it miss log to say the jar couldn't be loaded

**Comment by loopnotzero** [comment]
Kafka should find it even if is it were built as not shaded jar because isolated plugin loader looking for sub types of base class Connector.
Just to be sure did you try to look inside container if your connector it's really present there?
