### ISSUE TITLE
Docker images need to be updated for cp-3.2.0

### ISSUE THREAD

**Issue by atharvai** [confluentinc/cp-docker-images#227]
I'm using Kafka Connect  image 3.1.2 whi which was released 19hours ago according to DockerHub. I don't see any images for 3.2.0. When will these be released with the new S3 connector bundled?

ref:
https://hub.docker.com/r/confluentinc/cp-kafka-connect/
https://github.com/confluentinc/kafka-connect-storage-cloud

**Comment by arrawatia** [comment]
We just uploaded the latest version of 3.2.0 images with S3 connector. Please check it out on Dockerhub.

**Comment by atharvai** [comment]
awesome thanks!
