### ISSUE TITLE
Replace cub -z with -b for REST proxy and Schema registry

### ISSUE THREAD

**Issue by arrawatia** [confluentinc/cp-docker-images#228]
REST proxy and Schema registry as they use the new consumer and don't depend on Zookeeper.

**Comment by simplesteph** [comment]
@arrawatia 
- Can the new REST Proxy start without Zookeeper config?
- The Schema registry still uses Zookeeper to create their own node for master election as far as I know

**Comment by arrawatia** [comment]
You are correct, REST proxy and SR both still need access to zookeeper. Thanks for pointing this out !

I thought we had removed the REST proxy dependency but apparently it still needs Zookeeper for backward compatibility.

Closing this until we finally get rid of ZK dependencies :).
