### ISSUE TITLE
Deploying zk/kafka cluster in docker swarm -Cannot open channel to X at election address

### ISSUE THREAD

**Issue by infsaulo** [confluentinc/cp-docker-images#241]
Hi,

I'm trying to deploy a cluster of 3 instances of zookeeper/kafka nodes on a swarm of 3 machines on cloud. I'm getting a specific error saying I cannot open channel X at a given election address when starting my zookeeper instances. Is it possible to deploy a zk/kafka cluster using `docker swarm`, through `docker stack deploy` command? (The ports 2888 and 3888 are opened and already checked that on my machine instances)

I had created this docker-compose.yml bellow to be deployed with `docker stack deploy`:

    version: "3"
    services:
    zk:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_SERVER_ID: $ZK_SERVER_ID
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: $ZK_CLUSTER_URL
        deploy:
            mode: global
            placement:
                constraints: [node.labels.zookeeper == true]

    kafka:
        image: confluentinc/cp-kafka:latest
        environment:
            KAFKA_BROKER_ID: $KAFKA_BROKER_ID
            KAFKA_ZOOKEEPER_CONNECT: $ZK_KAFKA_CLUSTER_CONN_URL
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$EXTERNAL_IP:9092
        depends_on:
            - zk
        deploy:
            mode: global
            placement:
                constraints: [node.labels.kafka == true]

In each machine I have the environment variables `ZK_SERVER_ID` and `KAFKA_BROKER_ID` defined and unique between them. Specifically the environment variable `ZK_CLUSTER_URL` where I define the connection url of my zookeeper cluster is the internal IP of each machine that compound the swarm `internalip1:2888:3888;internalip2:2888:3888,internalip3:2888:3888`

Unfortunately, I'm getting the following error when deploying my zookeeper cluster, from command `docker service logs <service_zk_name>` from the swarm node machine I deployed(10.28.0.9):

    kafka_cluster_zk.0.yw2lxug3gdoy@m4    | [2017-04-02 16:30:28,468] INFO My election bind port: /10.28.0.9:3888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    | [2017-04-02 16:30:28,468] ERROR Exception while listening (org.apache.zookeeper.server.quorum.QuorumCnxManager)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    | java.net.BindException: Cannot assign requested address
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at java.net.PlainSocketImpl.socketBind(Native Method)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at java.net.ServerSocket.bind(ServerSocket.java:375)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at java.net.ServerSocket.bind(ServerSocket.java:329)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:537)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    | [2017-04-02 16:30:28,917] WARN Cannot open channel to 2 at election address /10.28.0.14:3888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    | java.net.ConnectException: Connection refused
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at java.net.PlainSocketImpl.socketConnect(Native Method)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at java.net.Socket.connect(Socket.java:589)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:381)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:426)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:843)
    kafka_cluster_zk.0.yw2lxug3gdoy@m4    |         at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:822)

**Comment by MohammadMazraeh** [comment]
Did you managed to run it using docker stack?

**Comment by alighanem** [comment]
Hello,

The issue is closed without comments. Was it fixed?
