### ISSUE TITLE
SCHEMA_REGISTRY_PORT Deprecated but still required

### ISSUE THREAD

**Issue by awebneck** [confluentinc/cp-docker-images#280]
When launching, the SCHEMA_REGISTRY_PORT env var is defined and populated automatically, even if not supplied. There is a deprecation warning in the Docker configs that exits 1 if that variable is defined here https://github.com/confluentinc/cp-docker-images/blob/v3.2.1/debian/schema-registry/include/etc/confluent/docker/configure. Attempting to manually unset it gets past that issue, but when it actually attempts to start the schema registry, this error appears:
```
===> Launching schema-registry ...
[2017-06-21 18:03:58,508] ERROR Server died unexpectedly:  (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain)
io.confluent.common.config.ConfigException: Invalid value  for configuration port: Not a number of type INT
```

This occurs whether or not I have SCHEMA_REGISTRY_LISTENERS set, and I have reproduced on both v3.2.1 and 3.1.2

**Comment by awebneck** [comment]
nm, was caused by naming conflict

**Comment by josdotso** [comment]
@awebneck I'm seeing this with the kafka-rest container.  Can you recall where the naming conflict happened?

**Comment by dolfelt** [comment]
Me as well. Any thoughts @awebneck?
