### ISSUE TITLE
windows docker running kafka-stream-examples

### ISSUE THREAD

**Issue by LegendJ** [confluentinc/cp-docker-images#304]
After download kafka-streams-examples/docker-compose.yml and 
run `docker-compose up -d`
I can start zookeeper However when I look into the docker-compose logs
I notice there is an error ` org.apache.kafka.common.KafkaException: io.confluent.metrics.reporter.ConfluentMetricsReporter ClassNotFoundException exception occurred
kafka_1                       |         at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:288)
kafka_1                       |         at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
kafka_1                       |         at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:102)
kafka_1                       |         at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:49)
kafka_1                       | Caused by: java.lang.ClassNotFoundException: io.confluent.metrics.reporter.ConfluentMetricsReporter
`
How should deal with it?

**Comment by gchiam** [comment]
@LegendJ , did you get this resolved? I am having the same problem.

**Comment by Loernl** [comment]
@LegendJ @gchiam  Have you solved the same mistake
