### ISSUE TITLE
Should KAFKA_REST_HOST_NAME be required?

### ISSUE THREAD

**Issue by jalaziz** [confluentinc/cp-docker-images#315]
The Kafka REST proxy configuration lists `host.name` as an optional configuration field. However, the docker image requires `KAFKA_REST_HOST_NAME` to be set.

Is the mismatch on purpose?

**Comment by jalaziz** [comment]
Nevermind. Just found the documentation that explains the reasoning.

**Comment by kn96** [comment]
can you post the link.
also what did you specify the  `KAFKA_REST_HOST_NAME` as??

**Comment by jalaziz** [comment]
@kn96 https://github.com/confluentinc/cp-docker-images/blob/99168d4003f6100488f3f07639becdc8b0da624b/docs/configuration.rst#required-settings-4

I ended up not needing to use Kafka REST Proxy. However, I was just using the AWS public hostname initially. The goal was to to use specific hostnames under a custom domain.
