### ISSUE TITLE
Oracle jdbc-source-connector with cp-kafka-connect will result in http 500 error

### ISSUE THREAD

**Issue by TranceMaster86** [confluentinc/cp-docker-images#338]
When I try to add an oracle jdbc source connector in cp-kafka-connect via curl or the landoop frontend it will end up in a http 500 error.
To reproduce, feel free to clone my repo for that error: https://github.com/TranceMaster86/kafka-connect-oracle-error
In the readme I described how to reproduce the error.

It will hang up kafka-connect completely. All other connectors seems to stop working after I want to create an oracle jdbc source connector with a '@' in the connection string. I think this will be the main problem here. The oracle connection string looks like 'jdbc:oracle:thin:@hostname:port/service' or 'jdbc:oracle:thin:@hostname:port:SID'.

**Comment by TranceMaster86** [comment]
Opend a Ticket at the apache kafka jira too: https://issues.apache.org/jira/browse/KAFKA-5938

**Comment by ewencp** [comment]
It looks like it is timing out writing the config to Kafka for some reason. This seems odd if you're able to successfully register other connectors before you try to create this one.

/cc @confluentinc/connect

**Comment by TranceMaster86** [comment]
Thanks for reply to this issue. So I added other connectors to mysql and postgres. Tgat worked without a trouble. When I try to add that oracle db connector in the standalone version of kafka connect with confluent stuff included, it works as expected. So I think something is really odd in distributed mode here.

**Comment by rmoff** [comment]
I've updated the [KAFKA JIRA](https://issues.apache.org/jira/browse/KAFKA-5938) -- this configuration, including `@`, works fine. See the JIRA for more details & notes.

**Comment by TranceMaster86** [comment]
I tried it with a single cp-kafka-connect docker container. I think this is a single-node distributed kafka-connect and it is not working.

**Comment by TranceMaster86** [comment]
After we got some java and tcp dumps and had a look into the code, we got a working solution. When you set the kafka connect parameter "schema.pattern" to the already given configuration, it worked fine in distributed mode and with the cp kafka connect container. Seems that the metadata fetching needs some time if you don't set a schema

**Comment by rhauch** [comment]
@TranceMaster86, glad you got it working. BTW, the time required to fetch the table metadata is a function of the database and the number of tables accessible to the database user. The next release of the JDBC connector will include [a change](https://github.com/confluentinc/kafka-connect-jdbc/pull/273) that improves the performance quite a bit. However, you can always use a database user that has access to only the tables you want.

So can we close this issue?

**Comment by TranceMaster86** [comment]
Yes of course

**Comment by arunkrishom** [comment]
How to add oracle jdbc driver in to confluent image in docker .. by default it has postgre sql and sqlite jdbc driver.

**Comment by rmoff** [comment]
See: https://rmoff.dev/fix-jdbc-driver-video / https://rmoff.dev/fix-jdbc-driver
