### ISSUE TITLE
When confluent docker image will pick up Kafka 0.11.0.1?

### ISSUE THREAD

**Issue by sophieqianCA** [confluentinc/cp-docker-images#363]
Apache Kafka released  version [0.11.0.1](https://archive.apache.org/dist/kafka/0.11.0.1/RELEASE_NOTES.html
) on September 13, 2017.

It fixed some issues we encountered.  

Since we are using Confluent 3.3.0.  ( It's using Apache Kafka 0.11.0.0, the latest stable version of Kafka. ).

Any timeline on when  the next release of Confluent ( which has 0.11.0.1 apache kafka ) will come out? 

Thanks

Sophie

**Comment by ewencp** [comment]
@sophieqianCA There should be an update coming out in a couple of weeks.

**Comment by sophieqianCA** [comment]
@ewencp Thank you very much  for the update.

**Comment by rusnyder** [comment]
This update is now out as a part of the 3.3.1 container (published to Docker Hub November 14, 2017).  Feel free to close this one!
