### ISSUE TITLE
CP Docker images and Log4j. 

### ISSUE THREAD

**Issue by bencoughlan** [confluentinc/cp-docker-images#367]
Hi there, 

Are you going to fix the log4j binaries across these images? 

The following works for kafka-connect, as a log4j properties.template file that we mount over the default file.

It pipes log files out to mounted storage, and has a rolling policy, which compresses the files after an hour.  

```

log4j.rootLogger={{ env["CONNECT_LOG4J_ROOT_LOGLEVEL"] | default('INFO') }}, FILE

log4j.appender.FILE=org.apache.log4j.rolling.RollingFileAppender
log4j.appender.FILE.File=/opt/logs/connect.log
log4j.appender.FILE.RollingPolicy=org.apache.log4j.rolling.TimeBasedRollingPolicy
log4j.appender.FILE.RollingPolicy.ActiveFileName =/opt/logs/connect.log
log4j.appender.FILE.RollingPolicy.FileNamePattern=/opt/logs/connect.%d{yyyyMMdd.HH}.gz
log4j.appender.FILE.layout = org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=[%d] %p %m (%c)%n
log4j.appender.FILE.ImmediateFlush=true

{% if env['CONNECT_LOG4J_LOGGERS'] %}
{% set loggers = parse_log4j_loggers(env['CONNECT_LOG4J_LOGGERS']) %}
{% for logger,loglevel in loggers.iteritems() %}
log4j.logger.{{logger}}={{loglevel}}, FILE
{% endfor %}
{% endif %}

```
This makes it a lot easier to manage the cluster, and should we need to send logs to confluent, in the event of downtime, it makes it really convenient. It also saves on JVM, as we flush quite often.

However, it only works with kafka connect, because every image in the docker suite is rolling with a different version of Log4j, something that hasn't been updated since 2011. 

Can we standardize these? It's literally a case of putting the kafka-connect log4j binary, and addon, in every image, I can submit the necessary the PR if you like? 

I've been talking to Confluent tech support for the past 12 months about this, and was promised it would be in the next update, but the list of changes coming down the line doesn't mention it anywhere.

**Comment by cmccabe** [comment]
Hi Ben,

It is definitely true that not every Confluent docker image has an "escape valve" that allows you to configure additional log4j loggers.  The connect docker image has CONNECT_LOG4J_LOGGERS, and the Kafka docker image has KAFKA_LOG4J_LOGGERS, but there is no way to configure ZK to have additional loggers.  Would adding this feature be useful to you?

> However, it only works with kafka connect, because every image in the docker suite is rolling with a different version of Log4j, something that hasn't been updated since 2011.

Hmm.  Every Confluent docker image I checked has contained `log4j-1.2.17.jar`, not an earlier or later version.  Perhaps the situation was different with older versions?  What version are you using?  Also, even if the versions were different, how would this prevent you from configuring logging?  I do not think that the configuration format has changed dramatically in recent years.

> Can we standardize these? It's literally a case of putting the kafka-connect log4j binary, and addon, in every image, I can submit the necessary the PR if you like?

I'm not sure I follow.  The log4j binary in kafka-connect is not different from that in other docker images.  Perhaps you mean this file?  https://github.com/confluentinc/cp-docker-images/blob/3.3.x/debian/kafka-connect-base/include/etc/confluent/docker/log4j.properties.template

**Comment by bencoughlan** [comment]
Hi Patrick, 

Thanks for the response. 

Kafka Connect has the necessary addon to allow for a RollingFileAppender, which will allow me to gzip the log files, and archive them, none of the other elements have them. 

http://logging.apache.org/log4j/extras/

The reason why we need to gzip these files is down to the sheer size of the log's that Kafka generates, It doesn't take long to fill a disk with debug enabled, even intermittently. having the option to zip the files up would make life a lot easier. It would also be really sweet if this could be done via env variables handed in, but I'll happily settle for the extra package. 

Cheers, 
Ben

**Comment by cmccabe** [comment]
Hi Ben,

Thanks for clarifying.  One thing that confused me about your comments earlier is that `RollingFileAppender` is part of `log4j-1.2.17.jar` itself, and doesn't require any additional jars to function.

```
$ jar tvf ./tools/build/dependant-libs-2.11.12/log4j-1.2.17.jar | grep Rolling
  5777 Sun May 06 13:00:32 PDT 2012 org/apache/log4j/DailyRollingFileAppender.class
  1813 Sun May 06 13:00:32 PDT 2012 org/apache/log4j/RollingCalendar.class
  4383 Sun May 06 13:00:34 PDT 2012 org/apache/log4j/RollingFileAppender.class
```

However, it does seem like some additional functionality is available in `apache-log4j-extras`.  I wasn't able to find a concise description of what that additional functionality is online, but perhaps compression is one of those things?

> Kafka Connect has the necessary addon to allow for a RollingFileAppender, which will allow me to gzip the log files, and archive them, none of the other elements have them.

This isn't really a docker issue, though, right?  Rightly or wrongly, Apache Kafka has never packaged `apache-log4j-extras`.  The docker image just reflects the jars that the project distributes.

Perhaps we should open a discussion about including apache-log4j-extras in the next Kafka release (and possibly backporting it to some of our bug fix releases).  I'm not familiar enough with log4j to know the pros and cons (if any).  I do know that many people want to upgrade to log4j2, but so far that has not happened.

**Comment by cmccabe** [comment]
By the way, I focused on Kafka in my answer because unless Kafka ships apache-log4j-extras, we would probably not want the rest of CP to ship it. :) kafka-connect has it only because one of the other projects that kafka-connect depends on pulled it in.

**Comment by bencoughlan** [comment]
Hi Colin, 

They're moving to sflog4j, 

I've submitted a PR to Apache for this, so hopefully it'll end up in the next release.

**Comment by cmccabe** [comment]
Hi Ben,

Do you mean slf4j?  slf4j is a "logging facade" which still requires an underlying library, such as log4j, log4j2, or logback.  Migrating to slf4j will not help with the issue you describe here-- the absence of the log4j-extras jar from the Apache Kafka release.  I have started a discussion on the upstream mailing list about log4j-extras.

**Comment by jorkzijlstra** [comment]
Why Log4J still being used? It was [marked as end of life](https://blogs.apache.org/foundation/entry/apache_logging_services_project_announces) about 3 years ago.

I have actually been looking into using slf4J with logback for Kafka Connect (we need json output with some fields renamed and environmental variables support). 
It seems that the `log4j.properties.template` is being parsed with some [custom logic](https://github.com/confluentinc/confluent-docker-utils/blob/master/confluent/docker_utils/dub.py). This does support the change to a custom layout and the use of environmental variables.

The official existing [V1 layout](https://github.com/logstash/log4j-jsonevent-layout) only don't support the renaming of fieldnames. So I'm now stuck in writing my own log4J extension on the V1 Layout.

Is there any plan on the roadmap in upgrading Log4J (switching to Slf4J or at least upgrading to Log4J2)?

**Comment by bagipriyank** [comment]
@jorkzijlstra were you able to log in json format?
