### ISSUE TITLE
Connect with SASL_PLAINTEXT does not work

### ISSUE THREAD

**Issue by jomach** [confluentinc/cp-docker-images#385]
Hi guys, I think I found a bug in the docker image. 
The properties file are correct created with this I mean security.protocol appears on the /etc/kafka-connect/kafka-connect.properties file.

the problem lies on the link bellow. 

https://github.com/confluentinc/cp-docker-images/blob/0eb1a62877ddd7688e2438bb61f29c88f88bb511/debian/kafka-connect-base/include/etc/confluent/docker/ensure#L24
I think this should be || instead of && .  Do I see it wrong ?

**Comment by thiagonache** [comment]
actually, the first comparison is an and operation, but it should have another comparison.
 if [[[ -n "${CONNECT_SECURITY_PROTOCOL-}" ]] && [[ $CONNECT_SECURITY_PROTOCOL = "SSL" ]] || [[ -n "${CONNECT_SECURITY_PROTOCOL-}" ]] && [[ $CONNECT_SECURITY_PROTOCOL = "SASL_SSL" ]]]

does it make sense?

**Comment by thiagonache** [comment]
and it's duplicated with #356

**Comment by thiagonache** [comment]
for me, after that, cub kafka-ready fails, because we need to add jaas configuration.

**Comment by thiagonache** [comment]
I've submitted https://github.com/confluentinc/cp-docker-images/pull/390

**Comment by thiagonache** [comment]
https://github.com/confluentinc/cp-docker-images/pull/392 merged to fix it on master.

**Comment by ewencp** [comment]
Closing as @thiagonache indicates this has been fixed now.
