### ISSUE TITLE
Latest image doesn't contain bundled connectors

### ISSUE THREAD

**Issue by buinauskas** [confluentinc/cp-docker-images#387]
I've copied over `docker-compose.yml` from https://github.com/confluentinc/cp-docker-images/tree/3.3.x/examples/cp-all-in-one and started the image.

Previously, I used to get all the bundled connectors, such as JDBC, Elasticsearch, HDFS, S3, now I don't.

All I'm getting is FileStreamConnector (both Source and Sink versions).

**Comment by wintersommer** [comment]
same here - we also want to include some external connectors like INFLUXDB and so on

**Comment by wintersommer** [comment]
I GOT IT, just add the environment variables like:

   CONNECT_PLUGIN_PATH: "/usr/share/java/kafka-connect-elasticsearch"

**Comment by buinauskas** [comment]
Closing as @wintersommer nailed it.

**Comment by echo-xu** [comment]
Not sure if you guys came across same issue, the doc https://docs.confluent.io/current/connect/userguide.html @ installing plugins mentioned the plugin path is a comma-separated list of directories, while during my testing it can only be a single path
> Kafka Connect finds the plugins using its plugin path, which is a comma-separated list of directories defined in the Kafka Connect’s worker configuration. To install a plugin, place the plugin directory or uber JAR (or a symbolic link that resolves to one of those) in a directory listed on the plugin path, or update the plugin path to include the absolute path of the directory containing the plugin.

**Comment by buinauskas** [comment]
@echo-xu I've got my docker-compose configured as follows and it works for me:

`CONNECT_PLUGIN_PATH: /etc/kafka-connect/jars,/usr/share/java/kafka-connect-elasticsearch`

I get all of my desired plugins that are in these folders
