### ISSUE TITLE
How to execute a connector worker at "docker-compose up"

### ISSUE THREAD

**Issue by fizxmike** [confluentinc/cp-docker-images#460]
I've been digging in the documentation [here](https://docs.confluent.io/current/connect/managing.html) and [here](https://docs.confluent.io/current/installation/docker/docs/tutorials/connect-avro-jdbc.html), but all I can find were "dynamic" way of executing a connector worker (in stand-alone or clustered mode) from the command line:

`bin/connect-standalone worker.properties connector1.properties [connector2.properties connector3.properties ...]`

or

```
curl -X POST \
  -H "Content-Type: application/json" \
  --data '{ "name": "quickstart-jdbc-source", "config": { "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector", "tasks.max": 1, "connection.url": "jdbc:mysql://127.0.0.1:3306/connect_test?user=root&password=confluent", "mode": "incrementing", "incrementing.column.name": "id", "timestamp.column.name": "modified", "topic.prefix": "quickstart-jdbc-", "poll.interval.ms": 1000 } }' \
  http://$CONNECT_HOST:28083/connectors
```

Are we assuming deployment to be a two step process? Like "docker-compose up" then, "exe-connectors.sh" some time later (or actually poll for "ready" state then execute connector workers).

What is the recommended way to "automatically" execute a connector worker at deployment time?

**Comment by cricket007** [comment]
Well, the container will launch the REST Service on startup. You will need to POST the initial config. On the second instance, however, it will automatically pick up where you left off. 

Therefore, the workaround I am proposing is manually producing the necessary messages to the `config` topic for the connect worker group.

**Comment by fizxmike** [comment]
Well, I suppose there is no official way to acheive what I want. (Are you proposing doing a docker commit after posting the connector config?)

Regardless, It seems like I might need to write my own manager (c# dotnet core port of confluent.sh) since we are deploying on docker for windows in production. Maybe you know of someone who has done this already?

**Comment by cricket007** [comment]
Not sure what `docker commit` does, but I meant using `kafka-console-producer` after creating the config topic manually (as per the Connect instructions), waiting for that command to finish, and then starting the Connect container.

And no, I've never used Docker for Windows or know anyone using it in Production. Also, not seeing why you need to rewrite the `confluent` binary. That's not a production script anyway, and is only intended for local use development. There already are equivalent Windows binaries for `kafka-run-class` and `connect-distributed`

**Comment by fizxmike** [comment]
What I'm wanting is a "docker-compose up" deployment of not only CP, but all my connectors and producers/consumers.

Anyway, I've settle for creating a very minimal "bootstrap" container that will poll and wait for connector to be ready, then inject my connector configs. (whether I will utilize confluent-cli or dotnet core custom implementation of the API; I do not know).

If anyone has any better ideas (**like a magical place to put connector parameters in the container to have them load automatically**), please LMK.

PS the [confluent CLI is actually a bash script](https://github.com/confluentinc/confluent-cli/blob/master/src/oss/confluent.sh) wrapping a bunch of curl and other things (which windows PowerShell and cmd do not support)... It also looks like it's use case is development only (since it asks you to point to "CONFLUENT_HOME").

**Comment by cricket007** [comment]
> whether I will utilize confluent-cli or dotnet core custom implementation of the API; I do not know

You really just need like `busybox` container, or anything with `curl` and `netcat` with some JSON files in a volume mount for your config properties to [wait for the connect port to open](https://stackoverflow.com/questions/27599839/how-to-wait-for-an-open-port-with-netcat), then `POST -d@connect-config.json connect:8083/connectors`

`confluent-load` will indeed only apply to a [local instance of Connect](https://github.com/confluentinc/confluent-cli/blob/master/src/oss/confluent.sh#L1228). 

Also, [see note](https://docs.confluent.io/current/cli/index.html#cli)

>> The Confluent CLI is meant for development purposes only and is not suitable for a production environment. The data that are produced are transient and are intended to be temporary

I agree it would be useful to add [an init volume directory like MySQL](https://github.com/mysql/mysql-docker/blob/mysql-server/5.7/docker-entrypoint.sh#L150-L156) to automatically load some property files on start. 

Feel free to raise a PR.   
Note: it would have to be [after this line](https://github.com/confluentinc/cp-docker-images/blob/master/debian/kafka-connect-base/include/etc/confluent/docker/launch#L42), which runs the container's `exec` call to run the server.

**Comment by fizxmike** [comment]
Thanks for helping me work this out. I will go "busybox" route for now with "wait for open port" trick, if that turns out "clean" enough, there is no need for PR. CHEERS!

**Comment by cricket007** [comment]
Btw, I updated #467 with a "wait for port" example from within the container itself
