### ISSUE TITLE
CONNECT_BOOTSTRAP_SERVERS 

### ISSUE THREAD

**Issue by MrBuddyCasino** [confluentinc/cp-docker-images#466]
We use the following list of bootstrap hosts:
`zookeeper-1.apps.local:2181,zookeeper-2.apps.local:2181,zookeeper-3.apps.local:2181/kafka`

This works for schema-registry and rest, but not for connect ('latest'). On startup we get: `org.apache.kafka.common.config.ConfigException: Invalid url in bootstrap.servers: zookeeper-3.apps.local:2181/kafka`. 

Is this supposed to work? Do I have to use Kafka hosts instead of Zookeeper? 

Also, the documentation for CONNECT_BOOTSTRAP_SERVERS says "A unique string that identifies the Connect cluster group this worker belongs to.", which seems to belong to CONNECT_GROUP_ID (see https://docs.confluent.io/current/installation/docker/docs/configuration.html#kafka-connect)

**Comment by cricket007** [comment]
"Bootstrap" commonly refers to the Kafka servers, not the ZK Connect string.

https://docs.confluent.io/current/connect/userguide.html#common-worker-configs

> A list of host/port pairs to use for establishing the initial connection to **the **Kafka cluster

**Comment by MrBuddyCasino** [comment]
Done: https://github.com/confluentinc/cp-docker-images/pull/478

**Comment by cricket007** [comment]
Thanks. Feel free to close this issue.
