### ISSUE TITLE
How to set multiple ips/ports

### ISSUE THREAD

**Issue by JemiloII** [confluentinc/cp-docker-images#470]
https://github.com/confluentinc/cp-docker-images/blob/1148be711166b6f620a0ce49d29816ecf2d47d39/debian/kafka/include/etc/confluent/docker/configure#L31

Why is it doing this? I need to set multiple ip locations and sets them all to 0.0.0.0 and then complains that having PLAINTEXT://0.0.0.0:9092 & PLAINTEXT://0.0.0.0:9093

I am using the docker network and need to set PLAINTEXT://kafka:9093 for my docker network and keep PLAINTEXT://kafka:9092 for my system and other tools. kafka:9093 ends up being an internal docker ip, managed and setup by docker-compose/swarm. I can't have my tools or other apps connect that would normally connect via localhost:9092

**Comment by cricket007** [comment]
@JemiloII , Please use the protocol map as shown in the Compose files. 

https://github.com/confluentinc/cp-docker-images/blob/5.0.0-post/examples/cp-all-in-one/docker-compose.yml#L26-L27

Then you can use `localhost:29092` for clients outside the docker network and `kafka:9092` for those inside

**Comment by JemiloII** [comment]
Thanks a bunch!

**Comment by cricket007** [comment]
Welcome 👍 

Feel free to close this
