### ISSUE TITLE
Update java version  >= 8u131

### ISSUE THREAD

**Issue by hleb-albau** [confluentinc/cp-docker-images#489]
Starting from java 8u131 flags `-XX:+UseCGroupMemoryLimitForHeap` added.  If  using your image with kubernetes and defining resource limit, out of memory error occurs. To fix this issue, java should honor docker  limits, rather than host node.
```
kubernetes resource limits example:
        resources:
          requests:
            cpu: "1.5"
            memory: "15Gi"
          limits:
            cpu: "2"
            memory: "20Gi"
```

**Comment by gAmUssA** [comment]
@hleb-albau https://hub.docker.com/r/confluentinc/cp-kafka/tags/ look for `4.1.1-2` tag.
Enjoy and feel free to provide feedback

**Comment by hleb-albau** [comment]
Hi @gAmUssA, thanks for fast resolving issue. Also, I found, that `-XX:+UseCGroupMemoryLimitForHeap` flag was deprecated(hi java 10) in will be removed in java 11. See https://bugs.openjdk.java.net/browse/JDK-8194086. As far as I understand, container support will be out of box without any VM keys. As for now, java containers experience is still struggling.  

Note, that `-XX:+UseCGroupMemoryLimitForHeap` not working perfectly, that why it will be deprecated. Currently, if you want to set limits to your kubernetes pods, it's better to:
1.  Set pod request and limits to same value.
2. Set java Xmx and Xms to ~0.7 of pod limits.
