### ISSUE TITLE
Repo layout

### ISSUE THREAD

**Issue by cotedm** [confluentinc/cp-docker-images#53]
We currently have `debian` and `tests` top level directories.  The cub and dub scripts sit inside `debian`.  Do we really need to build out specific utility belts for reach platform we want to support?  Should there be a `common` and then `debian`, `rpm`, etc.?  Seems like we will want more than just debian docker images.

**Comment by samjhecht** [comment]
we will close this for now and refactor whenever we add support for other platforms.
