### ISSUE TITLE
Confluent Control Center does not propagate some environment variables

### ISSUE THREAD

**Issue by angelbarrera92** [confluentinc/cp-docker-images#543]
Good night. 

It seems that the `confluent.controlcenter.kafka.<name>.bootstrap.servers` property is not spreading correctly in the configuration file. 

I've developed a couple of tests that prove the change I will propose. They are in the repository: https://github.com/angelbarrera92/confluent-docker-utils/tree/bugfix/control-center-template

Using the environment variable: 

`CONTROL_CENTER_CONFLUENT_CONTROLCENTER_KAFKA_MYCLUSTER_BOOTSTRAP_SERVERS=kafka:9092`

Generates the following line in control center configuration file:

`confluent.controlcenter.confluent.controlcenter.kafka.mycluster.bootstrap.servers=kafka:9092`

The expected value is: 

`confluent.controlcenter.kafka.mycluster.bootstrap.servers=kafka:9092`

I am going to propose a pull request to solve this case.

**Comment by rancp** [comment]
@angelbarrera92 if you just use `CONTROL_CENTER_KAFKA_MYCLUSTER_BOOTSTRAP_SERVERS` it should generate `confluent.controlcenter.kafka.mycluster.bootstrap.servers`

**Comment by angelbarrera92** [comment]
@rancp Good Morning. 

Thanks! seems to work!

Solved!
