### ISSUE TITLE
Kafka MQTT Docker image not available on Docker Hub

### ISSUE THREAD

**Issue by gschmutz** [confluentinc/cp-docker-images#549]
The Kafka MQTT Docker image is not available on Docker Hub. Any reason for that or has it been forgotten? Thanks!

**Comment by gAmUssA** [comment]
@gschmutz There is some glitch in build infra. images will be available shortly. Thank you for your message!

**Comment by gAmUssA** [comment]
@gschmutz 
https://hub.docker.com/r/confluentinc/cp-kafka-mqtt/

**Comment by gschmutz** [comment]
Thanks for the quick response and for making it available!
