### ISSUE TITLE
502 Bad Gateway in Control Center KSQL Tab

### ISSUE THREAD

**Issue by btull89** [confluentinc/cp-docker-images#559]
I'm stuck at the `Creating Streams and Tables` step of the Confluent Enterprise Docker Quickstart.
https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html#create-streams-and-tables

The control center will not load the KSQL section due to a 502 bad gateway.

I'm on windows using virtualbox to host the vm running CentOS7.
![from browser](https://user-images.githubusercontent.com/7583648/43921871-ac8b317e-9be2-11e8-96f8-91cfa5ddc2c9.png)

![control-center logs](https://user-images.githubusercontent.com/7583648/43921765-5ed765d8-9be2-11e8-9228-7496c43c826b.png)

**Comment by btull89** [comment]
I found the issue.
We are using the `vagrant` domain for other applications that have rather large cookies (size 4K).
After deleting these cookies from the browser, the http request worked and so does the dashboard.

**Comment by gAmUssA** [comment]
@btull89 Thanks for letting us know! 
Closing now
