### ISSUE TITLE
Manifest for confluentinc/cp-zookeeper:5.1.0 not found

### ISSUE THREAD

**Issue by willvelida** [confluentinc/cp-docker-images#582]
When I try run `sudo docker-compose up -d` in Ubuntu 18.04, I get the following error message:

ERROR: manifest for confluentinc/cp-zookeeper:5.1.0 not found

I've tried just removing the folder and recloning the project, but not really sure what to do here.

Any help would be great :)

**Comment by willvelida** [comment]
This is regarding the open source version

**Comment by buithi** [comment]
To quickly fix, maybe change line 5 to "image: confluentinc/cp-zookeeper:latest"

**Comment by willvelida** [comment]
That worked thanks :). Is there a specific reason why each image has a specified version number?

**Comment by jschulenklopper** [comment]
In my case, changing the version for `cp-zookeeper` to `latest` wasn't the only change necessary. I had to do the same for `cp-enterprise-kafka`, `cp-schema-registry`, `cp-kafka-connect` and a couple of others. The 5.1.0 versions do not seems to be available (publicly) at the Docker registry?

**Comment by calvaradocl** [comment]
Hi, I was trying out the docker images and I made the same changes in my files, but I'm having trouble running the ksq-datagen image, I was inspecting the logs and I have the following error:

```
ksql-datagen       | [main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka version : 2.0.0-cp1
ksql-datagen       | [main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka commitId : c0a49b648f43f57d
ksql-datagen       | Waiting for Confluent Schema Registry to be ready...
ksql-datagen       | Waiting a few seconds for topic creation to finish...
ksql-datagen       | cp: cannot stat '/usr/share/java/monitoring-interceptors/monitoring-interceptors-5.1.0.jar': No such file or directory
```
Is there any workaround for this issue? Currently I'm following the docker Quickstart.

**Comment by jschulenklopper** [comment]
Same here, to the dot. That file `/usr/share/java/monitoring-interceptors/monitoring-interceptors-5.1.0.jar` is likely to be missing in the `ksql-datagen` Docker image. Perhaps the just-before-latest tag is still in the Docker images that you're using now. Could be `5.0.0` (but I don't now which specific release version is currently tied to `latest`.

But as I said, perhaps this is shortly being solved (just by waiting) if the release of `5.1.0` is complete. It seems it's missing some final details just now.

**Comment by jschulenklopper** [comment]
It seems that the `5.1.0` tag has been set a bit too early, since that release isn't complete/released yet. See https://github.com/confluentinc/cp-docker-images/commit/afc4dfb315341c3f3e43e7e5bccfbb608301e5c2 for a recent discussion on this.

I managed to get things working after reverting back to that commit, which delivers a working version of the `docker-compose.yml` file. Effectively, I'm using the `5.0.0` version, for which the Docker images are available to run `docker-compose up` and generate sample data with `ksql-datagen`.

**Comment by calvaradocl** [comment]
Effectively, I used the docker-compose.yml file that you mentioned and I was able to run the data-gen container. Now I'm trying to figure out how to link the control-center container to the ksql-server.

**Comment by gmdatascience** [comment]
@calvaradocl While trying to generate data using below command, it raises error "ERROR: No containerfound for ksql-datagen_1". Any clue?

docker-compose exec ksql-datagen ksql-datagen quickstart=pageviews format=delimited topic=pageviews maxInterval=100 \
propertiesFile=/etc/ksql/datagen.properties bootstrap-server=broker:9092

**Comment by jschulenklopper** [comment]
Sometimes the container is stopped. What does `docker-compose ps` report? Or try `docker-compose up` once more.

**Comment by willvelida** [comment]
@gmdatascience 'docker-compose up -d' should work if ksql-datagen hasn't started. Best way to check is to run 'docker-compose ps' again and see if it's up. If not, compose it again :)

**Comment by rmoff** [comment]
Root cause for this is that the default branch was `master`, pointing to the as-yet-unreleased `5.1.0` version. 
We've switched the default branch to be in line with "latest". So currently that's branch `5.0.0-post`, which corresponds to `5.0.0` version of the docker images. 

Apologies for the problems. Please open a new issue (or head to http://cnfl.io/slack) if you still have problems.

**Comment by jschulenklopper** [comment]
> We've switched the default branch to be in line with "latest". So currently that's branch 5.0.0-post, which corresponds to 5.0.0 version of the docker images.

Great - checking out the `5.0.0-post` branch solved the problem earlier for me, so this change for `master` is a sane one. Thanks!

**Comment by rodolfod2r2** [comment]
> > We've switched the default branch to be in line with "latest". So currently that's branch 5.0.0-post, which corresponds to 5.0.0 version of the docker images.
> 
> Great - checking out the `5.0.0-post` branch solved the problem earlier for me, so this change for `master` is a sane one. Thanks!


I installed it to 5.0.0 and it is running flat
