### ISSUE TITLE
cp-all-in-one: ControlCenter KSQL configuration

### ISSUE THREAD

**Issue by ghotiphud** [confluentinc/cp-docker-images#591]
When running cp-all-in-one ControlCenter could not find the ksql cluster.  Uncommenting `CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"` in the `docker-compose.yml` file seems to fix this.  Should this change be made?

**Comment by ybyzek** [comment]
@ghotiphud : great catch.  Actually several changes need to be made for C3/KSQL integration to work in 5.0.0:

Add:

```bash
      CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"
      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://localhost:8088"
```

Remove:

```bash
      CONTROL_CENTER_KSQL_ENDPOINT: "http://ksql-server:8088"
```

**Comment by ghotiphud** [comment]
Ended up copying those same settings from the https://github.com/confluentinc/cp-demo repo, and can verify that they do fix the issue.

**Comment by ybyzek** [comment]
Great to hear!  I'm leaving this issue open until I commit the fix

**Comment by ybyzek** [comment]
I merged the fix and am now closing this issue
