### ISSUE TITLE
Kafka Connect v4.1.2 requires more memory

### ISSUE THREAD

**Issue by hectorgarzon** [confluentinc/cp-docker-images#593]
We were using kafka connect v3.2.2 and after upgrading to v4.1.2 it now requires much more memory.
It is deployed to k8s and it requires 2Gb without any connector running and it requires 3Gb when a simple file text sink is running.
When using v3.2.2 only 1G was required
Is there any configuration or solution to reduce this memory consumption?

Thanks

**Comment by hectorgarzon** [comment]
First, thanks for the info.
To be sure about your suggestion, do you mean that I have to decrease the value of Xmx using that variable KAFKA_HEAP_OPTS on theKafka instance? I'm running Connect on it's own docker container

Thanks

**Comment by cricket007** [comment]
Connect and the brokers share the same set of environment variables for those properties

**Comment by hectorgarzon** [comment]
Ok, thanks

**Comment by cricket007** [comment]
@hectorgarzon Feel free to close this ticket, if that answered your questions

**Comment by jocelyndrean** [comment]
Hi guys ! I fixed this issue with this:

KAFKA_HEAP_OPTS = "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"

**Comment by cricket007** [comment]
@jocelyndrean That only applies if running in a container or a systemd cgroup, correct?

**Comment by jocelyndrean** [comment]
Yes sorry you're right @cricket007 it's only a solution when you're running in a container 🙏
