### ISSUE TITLE
JMX monitoring on host via port map not working

### ISSUE THREAD

**Issue by paddypawprints** [confluentinc/cp-docker-images#601]
Hi,

I have kafka running in a container and wanted to attach a JMX monitoring tool that is running outside of the docker machine. I set up the port maps but it turns out there are some additional java startup parameters required. 
    -Djava.rmi.server.hostname IP address of the docker host 
    -Dcom.sun.management.jmxremote.rmi.port same value as $JMX_PORT

I modified the kafka-run-class script as follows at line 157 to get it working. An additional (optional) parameter - $KAFKA_JMX_RMI_HOST is set in the environment when running the container.

\# JMX port to use
if [  $JMX_PORT ]; then
  KAFKA_JMX_OPTS="$KAFKA_JMX_OPTS -Dcom.sun.management.jmxremote.port=$JMX_PORT  -Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT"
    # JMX RMI hostname - set to the host if using docker
    if [ $KAFKA_JMX_RMI_HOST ]; then
      KAFKA_JMX_OPTS="$KAFKA_JMX_OPTS -Djava.rmi.server.hostname=$KAFKA_JMX_RMI_HOST  -Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT"
    fi
fi

**Comment by paddypawprints** [comment]
The current scripts don't work when the remote monitor is on the host and the JMX port is port mapped. You need the additional JVM options.

**Comment by cricket007** [comment]
Not sure if this help, but might be worth taking a look at 

- https://docs.confluent.io/current/installation/docker/docs/operations/monitoring.html
- https://github.com/confluentinc/cp-docker-images/blob/5.0.0-post/docs/operations/monitoring.rst

**Comment by paddypawprints** [comment]
Ah, that is it. Makes sense, case closed.
