### ISSUE TITLE
Control-Center schema-registry configuration

### ISSUE THREAD

**Issue by rmh78** [confluentinc/cp-docker-images#643]
The configuration file for the confluent control center does not include the path to the schema registry.

**Configfile:**
cp-docker-images/debian/enterprise-control-center/include/etc/confluent/docker/control-center.properties.template

**Missing entry:**
confluent.controlcenter.schema.registry.url=<your_schema_registry_server>

See https://www.confluent.io/blog/june-preview-release-confluent-plaform/

**Comment by reinmh** [comment]
The solution is to set the environment variable CONTROL_CENTER_SCHEMA_REGISTRY_URL to http://schema-registry:8081

**Comment by rmh78** [comment]
works fine!
