### ISSUE TITLE
Packages distributed in insecure fashion (might get pwned)

### ISSUE THREAD

**Issue by brndnmtthws** [confluentinc/cp-docker-images#651]
Hey folks,

I wasn't sure where to file this issue, so I figured I'd put it here since it seems to be related to binary distribution.

Currently, the confluent packages are distributed over insecure HTTP without a way to verify the archive (as far as I can tell). The link is:

http://packages.confluent.io/archive/5.1/confluent-5.1.0-2.11.tar.gz

There is no SHA256 sum available (I think?), nor is the package itself signed.

Please add SHA256 sums, and enable TLS on your package archive endpoint.

Thanks!

**Comment by javabrett** [comment]
Does download https://packages.confluent.io/archive/5.1/confluent-5.1.0-2.11.tar.gz work? That would solve the TLS piece. Perhaps linking pages need update?

**Comment by brndnmtthws** [comment]
Didn't think to try that, but yes it works. Still, the website gives me the `http://` link by default. There's still no way to verify the archive (no hash or signature).

**Comment by javabrett** [comment]
For a checksum you can append `.sha1.txt` or `.sha256.txt` for https://packages.confluent.io/archive/5.1/confluent-5.1.0-2.11.tar.gz.sha1.txt or https://packages.confluent.io/archive/5.1/confluent-5.1.0-2.11.tar.gz.sha256.txt .

**Comment by brndnmtthws** [comment]
Good to know. It would be sweet if that was documented.
