### ISSUE TITLE
 docker-compose up -d --build 'security issue'

### ISSUE THREAD

**Issue by mattjones1990** [confluentinc/cp-docker-images#675]
Hi,

I'm getting the following issue when running 'docker-compose up -d --build' as per the tutorial at https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html#ce-docker-quickstart

See code below: 

```
PS C:\Users\jonesm7\cp-docker-images\examples\cp-all-in-one> docker-compose up -d --build
Building connect
Step 1/3 : FROM confluentinc/cp-kafka-connect:5.0.0
 ---> 7df8759460f7
Step 2/3 : ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"
 ---> Using cache
 ---> 435e2ea3ce2e
Step 3/3 : RUN confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:latest
 ---> Running in 1281ca71b0e6
Running in a "--no-prompt" mode
Unable to verify Confluent Hub's identity

Error: Security issues
ERROR: Service 'connect' failed to build: The command '/bin/sh -c confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:latest' returned a non-zero code: 5
```

This is on Windows 10 Enterprise.

**Comment by ybyzek** [comment]
@mattjones1990 sounds like the same issue as:

https://github.com/confluentinc/cp-docker-images/issues/654
https://github.com/confluentinc/cp-docker-images/issues/646

Note that Windows is apparently not supported with the confluent-hub-client, so consider trying this on mac or linux

**Comment by mattjones1990** [comment]
https://github.com/confluentinc/cp-docker-images/issues/654#issuecomment-448820269

Thanks for the reply. Seems that this comment above worked ^. It seems to go on some infinite loop last night which was odd, but then I ran the same command this morning and it worked instantly!

Thanks for the help.

**Comment by janjwerner-confluent** [comment]
This repository is no longer in use.
