### ISSUE TITLE
Bad server port in example ?

### ISSUE THREAD

**Issue by oterrien** [confluentinc/cp-docker-images#679]
In the bellow example, is it normal the schema-registry port is 8081 although the exposed port is 8085 ?

https://github.com/confluentinc/cp-docker-images/blob/a7a3c6f53ffb2c1ecdb79f38a074ab4f9d9021e6/examples/cp-all-in-one-cloud/docker-compose.yml#L159

https://github.com/confluentinc/cp-docker-images/blob/a7a3c6f53ffb2c1ecdb79f38a074ab4f9d9021e6/examples/cp-all-in-one-cloud/docker-compose.yml#L5-L20

**Comment by ybyzek** [comment]
@oterrien  this is a mistake, nice catch!  Did you want to submit a PR?

**Comment by oterrien** [comment]
@ybyzek no problem. https://github.com/confluentinc/cp-docker-images/pull/680

**Comment by ybyzek** [comment]
PR merged
