### ISSUE TITLE
Question: any plans to update OpenJDK version?

### ISSUE THREAD

**Issue by palmerabollo** [confluentinc/cp-docker-images#684]
The images are currently using OpenJDK 8 ([see cp-base Dockerfile](
https://github.com/confluentinc/cp-docker-images/blob/5.1.1-post/debian/base/Dockerfile#L59)). Are there any plans to upgrade to OpenJDK 9+?

**Comment by rkettelerij** [comment]
+1. Also interested here, see same question in #655

**Comment by palmerabollo** [comment]
Thanks. I'm closing this one in favor of #655.
