### ISSUE TITLE
cp-kafka image uses a vulnerable apache commons collections

### ISSUE THREAD

**Issue by seveas** [confluentinc/cp-docker-images#690]
```
$ docker run -ti --rm confluentinc/cp-kafka:5.1.1 ls /usr/share/java/kafka | grep commons-collections
commons-collections-3.2.1.jar
```
According to https://commons.apache.org/proper/commons-collections/security-reports.html, that version has security vulnerabilities. Would it be possible to update to 3.2.2?

**Comment by gAmUssA** [comment]
@seveas Thank you reporting this. We're looking on fixing this asap. 
Cheers,
Vik

**Comment by cricket007** [comment]
FWIW, I've forked and patched to 3.2.2, and it continues for work fine for the broker, registry, and connect images

**Comment by gAmUssA** [comment]
@seveas @cricket007  we're internally testing update image (5.1.2). Should be release soon. I will let you know when it will be available. 

Cheers,
Vik

**Comment by gAmUssA** [comment]
@seveas @cricket007 

it's was fixed 

```
❯ docker run -ti --rm confluentinc/cp-kafka:5.1.2 ls /usr/share/java/kafka | grep commons-collections
commons-collections-3.2.2.jar
```

Let me know if you need anything!

Cheers,
Vik

**Comment by cricket007** [comment]
Thanks! 

Would you happen to know if there is a 4.1.3 release on the way? I've noticed some patches being applied to that branch in other projects

**Comment by gAmUssA** [comment]
@cricket007 i know that 4.0.3 (ak 1.0.2) is brewing. don’t know anything about 4.1.3
