### ISSUE TITLE
How to create topics on docker container start-up?

### ISSUE THREAD

**Issue by pratapagiri** [confluentinc/cp-docker-images#694]
I'm using docker-compose to start zookeeper and Kafka using https://github.com/confluentinc/cp-docker-images/blob/5.1.1-post/examples/kafka-single-node/docker-compose.yml

Is there any way to create topics after Kafka starts running?

I'm looking for similar functionality provided by https://github.com/wurstmeister/kafka-docker#automatically-create-topics

Thanks

**Comment by ybyzek** [comment]
@pratapagiri have you seen [this example](https://github.com/confluentinc/examples/blob/5.1.1-post/microservices-orders/docker-compose.yml#L182-L215)?

**Comment by pratapagiri** [comment]
@ybyzek, 
Thanks for your suggestion. This works for me.
