### ISSUE TITLE
zookeeper jmx

### ISSUE THREAD

**Issue by fritchie** [confluentinc/cp-docker-images#700]
With the cp-kafka 5.1.1 docker image I am able to use the Prometheus JMX Exporter

https://github.com/prometheus/jmx_exporter

by adding the following environment variable:

KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.11.0.jar=8080:/opt/kafka.yml"

This does not seem to be possible with the cp-zookeeper 5.1.1 image. I have also tied the KAFKA_JMX_OPTS env var.

Is there be another way to pass is KAFKA_OPTS (KAFKA_JVM_OPTS)?

**Comment by cricket007** [comment]
I believe either should be correct. 

https://github.com/confluentinc/cp-docker-images/blob/5.1.2-post/debian/zookeeper/include/etc/confluent/docker/launch#L17-L20

But your `kafka.yml` has Zookeeper JMX beans defined in it?
