### ISSUE TITLE
Docker images don't work on ARM64

### ISSUE THREAD

**Issue by dchuyko** [confluentinc/cp-docker-images#718]
E.g. from the start there are not compatible binaries like
docker run -it --name zookeeper -p 2181:2181 confluent/zookeeper
standard_init_linux.go:190: exec user process caused "exec format error"

**Comment by gAmUssA** [comment]
@dchuyko Dima, ARM64 isn't officially supported platform.
it's x84_(64) at the moment  https://docs.confluent.io/current/installation/versions-interoperability.html

**Comment by dchuyko** [comment]
Ok. Should arm64v8/zookeeper work as a workaround?

**Comment by gAmUssA** [comment]
@dchuyko if you try could you report back how did it go?

**Comment by dchuyko** [comment]
It didn't work, but used LIberica JDK base images to build containers with Zookeeper and Kafka and it worked like a charm on my ARM server.

**Comment by tfindlay-au** [comment]
@dchuyko Would you be able to share any other details on your build ?
I would like to see if I can stand somehting on some NanoPiM4's, though even 4Gb of memory is limited and it may not be possible.

**Comment by IgorGerasimov** [comment]
@dchuyko  please share your work, if it possible - this will be really helpful - thank you.

**Comment by jonstelly** [comment]
If anyone is still interested in arm64 images I've got a pull request and some images up on docker hub.

https://github.com/confluentinc/cp-docker-images/pull/830

If anyone needs or wants images other than zookeeper and kafka, let me know.  I'm new to kafka and only interested in zookeeper and kafka right now so I'm probably not the best candidate for testing the other images.

**Comment by robdalo** [comment]
confluentinc/cp-kafka-connect, confluentinc/cp-schema-registry and confluentinc/cp-kafka-rest arm64 images would be good if possible.

> If anyone is still interested in arm64 images I've got a pull request and some images up on docker hub.
> 
> #830
> 
> If anyone needs or wants images other than zookeeper and kafka, let me know. I'm new to kafka and only interested in zookeeper and kafka right now so I'm probably not the best candidate for testing the other images.

**Comment by arslanakhtar61** [comment]
> confluentinc/cp-kafka-connect, confluentinc/cp-schema-registry and confluentinc/cp-kafka-rest arm64 images would be good if possible.
> 
> > If anyone is still interested in arm64 images I've got a pull request and some images up on docker hub.
> > #830
> > If anyone needs or wants images other than zookeeper and kafka, let me know. I'm new to kafka and only interested in zookeeper and kafka right now so I'm probably not the best candidate for testing the other images.

@gAmUssA Any update or plan on releasing arm64 compatible docker images for all of `confluentinc modules`? I want to deploy all confluentinc products docker images on my raspberry pi 4 running ubuntu 64-bit.

**Comment by ChristophDietrich** [comment]
It's also more interesting fir the upcoming ampere altra server systems which have 80-cores arm 64Bit architecture.

It's just a first feeling, but I guess this will be a big game changer.

Also think about that new Apple M1 chips are also based on arm. Mac Mini are used for server applications. We don't know how it's increase, but Amazone has now also instances available.

Will also to wait for arm support of your images 👍👍

**Comment by etolbakov** [comment]
@jonstelly Jon, thank you for creating `kymeric/cp-base`.
If anyone needs an Arm64 `schema-registry` image that works on Arm64 I'd like to share my workaround.
Either you can build the image on your laptop replacing schema-registry `Dockerfile` in [confluentinc/cp-docker-images](https://github.com/confluentinc/cp-docker-images/blob/5.3.1-post/debian/schema-registry/Dockerfile) with
https://gist.github.com/etolbakov/92c77f0c4cd4602afc7ce3800d5e1c65
or feel free to go with `eugenetea/schema-registry-arm64:latest` straightaway.

**Comment by danielgindi** [comment]
@etolbakov This is great! `eugenetea/schema-registry-arm64:latest` works, which completes the picture for me.

Should be pulled to the official repo and published to docker registry.

**Comment by andrewegel** [comment]
This in the same vein as https://github.com/confluentinc/cp-docker-images/pull/830 - This is a deprecated repo, no more enhancements will be going into it.

Please put your +1s behind https://github.com/confluentinc/common-docker/issues/117 for ARM support.

**Comment by fsan** [comment]
> @jonstelly Jon, thank you for creating `kymeric/cp-base`. If anyone needs an Arm64 `schema-registry` image that works on Arm64 I'd like to share my workaround. Either you can build the image on your laptop replacing schema-registry `Dockerfile` in [confluentinc/cp-docker-images](https://github.com/confluentinc/cp-docker-images/blob/5.3.1-post/debian/schema-registry/Dockerfile) with https://gist.github.com/etolbakov/92c77f0c4cd4602afc7ce3800d5e1c65 or feel free to go with `eugenetea/schema-registry-arm64:latest` straightaway.

I do not know the underlying reason why `eugenetea/schema-registry-arm64:latest` did not work for me (probably because versions of libraries I am using 🤔 ) but `watershine/cp-schema-registry:6.1.0-arm64` worked fine.

**Comment by rohit2b** [comment]
Hi folks,

Confluent has released Docker images for arm64 for development and testing purposes. Check it out across different Confluent Platform components in Docker Hub: https://hub.docker.com/u/confluentinc

For example, here's how to pull the latest CP Kafka image:

docker pull confluentinc/cp-kafka:latest.arm64
