### ISSUE TITLE
DockerHub page is returning 404

### ISSUE THREAD

**Issue by thethomp** [confluentinc/cp-docker-images#754]
I was looking to find all of Confluent's docker images, but the linked DockerHub page is returning a 404 error:
https://hub.docker.com/u/confluentinc/

![image](https://user-images.githubusercontent.com/73784/60914680-de22b780-a23e-11e9-8064-74da20b13538.png)

**Comment by ewencp** [comment]
This was a Docker Hub bug -- it looked like they were 404ing for any organization if you weren't logged in and a member of the organization. It appears to be fixed now. I'm going to close, but feel free to re-open if you are still seeing the issue.

**Comment by wuwu2000** [comment]
There is some regression?
Today I had exactly the same issue. I left my computer on the whole day. Every docker hub page like https://hub.docker.com/_/mariadb ended in 404 error pages.
I pressed "sign in" and immediatly was logged in (no login form). I was trying to reproduce this issue by logging off but the everything worked as expected. So there still is some issue when your cookie expires!?

**Comment by luzifer84** [comment]
Today it's obviously the other way around. Tried to find an image for isc dhcp servers and got in 7 of 8 cases a 404. After logout everything was fine.

**Comment by jontingvold** [comment]
I still see this whenever I try to see the status report  of a Docker Hub CI build or test on GitHub, whether I'm logged in or not.   

Today the status link was https://hub.docker.com/redirect/?resource_uri=/api/audit/v1/action/c3ce2af4-aa61-41c4-96cf-a750b804e32d/

**Comment by yonatanh20** [comment]
Today I've encountered a similar issue, the problem seemed to be was that my Email wasn't verified. Once I've verified my email address this problem went away. Some images were showing correctly and others were sent to 404.

**Comment by tp-duarte** [comment]
Hi there ! 

I'm having the same problem that @yonatanh20 with Docker Hub, but my e-mail is already verified. Don't know what I should do to see images logged in my account .

To pull the image that I wanted, I had to sign out.

**Comment by Abdulhadi-Mraish** [comment]
[SOLVED]
I verified my account mail, and it worked for me

**Comment by krunalijain** [comment]
after logging in from docker hub site i found the same issue $)$ page not found how to fix it someone please help

**Comment by krunalijain** [comment]
after logging in from docker hub site i found the same issue 404 page not found how to fix it someone please help

**Comment by LloydNicholson** [comment]
Same issue today with mcr.microsoft.com packages

**Comment by davidbarrowsatasos** [comment]
same issue today; search for "ASP.NET" and you get 404s.  Also the Microsoft images in the search results all say "undefined".
