### ISSUE TITLE
How can i know the kafka version packaged in Confluent

### ISSUE THREAD

**Issue by shizhengchao** [confluentinc/cp-docker-images#768]
> Docker image for deploying and running the version of Kafka packaged with Confluent Platform. The source code is currently available on Github. For the version of Kafka packaged in Confluent Community download, please see these images.

 please see these images, Infinite loop~！！！

**Comment by ewencp** [comment]
You can just look at the version in the filenames in the docker image, but we also maintain a mapping of Confluent Platform and Apache Kafka releases here: https://docs.confluent.io/current/installation/versions-interoperability.html#cp-and-apache-ak-compatibility
