### ISSUE TITLE
ccloud-generate-env-vars.sh script not running against ccloud config.json

### ISSUE THREAD

**Issue by pmid** [confluentinc/cp-docker-images#773]
I recently registered on Confluent Cloud, and I'm trying to follow the directions in https://github.com/confluentinc/cp-docker-images/tree/5.3.0-post/examples/cp-all-in-one-cloud .

When I launch ./ccloud-generate-env-vars.sh $HOME/.ccloud/config I have some problems:

Confluent Cloud Cli create a config file names 'config.json', but the script looks for 'config'
Also, the script seems to be written to work against a properties file, non a json : 
e.g. `grep "^bootstrap.server" $CCLOUD_CONFIG` looks for a row STARTING with 'bootstrap.server', and thus in the json it cannot find the property.

Am I missing something?

Regards,

Paolo

**Comment by ybyzek** [comment]
@pmid thanks for reporting this issue.  The new Confluent Cloud CLI does indeed generate a `config.json` instead of the previous version of Confluent Cloud CLI which generated a `config` properties file.

Workaround is to manually create that properties file, it should look something like this:

```bash
bootstrap.servers=<broker endpoint>
sasl.username=<api-key-id>
sasl.password=<secret-access-key>
basic.auth.credentials.source=USER_INFO
schema.registry.basic.auth.user.info=<username:password>
schema.registry.url=<sr endpoint>
```

**Comment by pmid** [comment]
@ybyzek Thanks a lot, I'll follow your advice.

Paolo
