### ISSUE TITLE
Latest tag is 6m old

### ISSUE THREAD

**Issue by nick-zh** [confluentinc/cp-docker-images#778]
Is it discouraged to use the latest tag or is there a problem that it doesn't point to the 5.3.0 images?

**Comment by cricket007** [comment]
In general, best practice of running any container is to always use a version tag so that you can guarantee that the image won't upgrade itself underneath you while you're using it. In other words, it prevents pulling newer images and doing a type of unintended, incompatible rolling release.

**Comment by nick-zh** [comment]
@cricket007 while this might be true for production in dev this might be different and i don't want to change my tags everytime a new release is out

**Comment by cricket007** [comment]
It appears that the Makefile does tag/push latest images

https://github.com/confluentinc/cp-docker-images/blob/5.3.1-post/Makefile

If you'd like to add additional tags, feel free to open a PR for review / discussion

**Comment by nick-zh** [comment]
@cricket007 thx for the feedback, could it be that something is amiss, if i check on dockerhub (https://hub.docker.com/r/confluentinc/cp-kafka/tags?page=2) i see that the latest tags is very old

**Comment by cricket007** [comment]
I'm honestly not sure how the Makefile is used, or how images actually get pushed to Dockerhub, but I do like the idea of adding major + major.minor tags.

**Comment by nick-zh** [comment]
@arrawatia @joel-hamill can you maybe shed light no this regarding the outdated latest tag
Also would you be open to a contribution to add major and major.minor tags or are there already plans for this?

**Comment by javabrett** [comment]
@nick-zh looks like the `latest` tag is now being regularly pushed, current is 9d old, so hopefully we can close this one.  Please comment here if that doesn't sound right and I'll re-open.
