### ISSUE TITLE
"Deprecation Notice" is unclear

### ISSUE THREAD

**Issue by pgarrison** [confluentinc/cp-docker-images#784]
The deprecation notice (in the readme) suggests that no one should use docker images with tags >= 4.2. Yet, there are images published on dockerhub up to 5.3, and they seem usable. I am not using maven, so the purpose of the dockerfile-maven-plugin is unclear.

It would help to explain what exactly is deprecated, for which use cases, and for what reason.

(I am using the 5.3 image, and would like to know if I should switch to [another image](https://hub.docker.com/r/bitnami/kafka).)

**Comment by rkettelerij** [comment]
FYI: https://github.com/confluentinc/cp-docker-images/pull/800
