### ISSUE TITLE
Connect's Internal converters configurations still required

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/cp-docker-images#797]
It appears that https://github.com/confluentinc/cp-docker-images/pull/761/ is incomplete.  It removed the check that those variables are defined (`dub ensure`) with the intention that docker images could remove the configs:

```
CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
```

However removing those config lines results in the Connect image failing:

```
kafka-connect      | /etc/confluent/docker/configure: line 36: CONNECT_INTERNAL_KEY_CONVERTER: unbound variable
```

The reason is that the code in the kafka-connect-base image references those variables anyway, and thus will fail if they're not set: https://github.com/confluentinc/cp-docker-images/blob/5.3.1-post/debian/kafka-connect-base/include/etc/confluent/docker/configure#L36. 

cc: @rmoff

**Comment by rspurgeon** [comment]
Occurs because of: https://github.com/confluentinc/cp-docker-images/blob/5.3.1-post/debian/base/include/etc/confluent/docker/bash-config#L16

```
set -o nounset
```

https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#The-Set-Builtin

set -u nounset
  same as -u

```
-u
    Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion. An error message will be written to the standard error, and a non-interactive shell will exit.
```

**Comment by rmoff** [comment]
Fixed with https://github.com/confluentinc/cp-docker-images/pull/805 and https://github.com/pulls
