### ISSUE TITLE
Kafka Connect - plugin.path not being picked up, only File connector found

### ISSUE THREAD

**Issue by brmakana** [confluentinc/cp-docker-images#818]
Running confluentinc/cp-kafka-connect-base:5.3.1, the plugin.path property does not seem to be picked up, causing only the FileStream source/sink connectors to be found.

I run the image like so:
```
docker run -it -p 8083:8083 --rm --name testing -e CONNECT_BOOTSTRAP_SERVERS="mykafkaserver:9092" \
        -e CONNECT_GROUP_ID="1" \
        -e CONNECT_CONFIG_STORAGE_TOPIC="connect_configs" \
        -e CONNECT_OFFSET_STORAGE_TOPIC="connect_offsets" \
        -e CONNECT_STATUS_STORAGE_TOPIC="connect_statuses" \
        -e CONNECT_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
        -e CONNECT_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
        -e CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
        -e CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
        -e CONNECT_REST_ADVERTISED_HOST_NAME="localhost" \
        confluentinc/cp-kafka-connect-base:5.3.1
```
I see this in the startup logs:
```
[2019-12-13 21:11:27,345] INFO DistributedConfig values: 
...
plugin.path = null
```

And when I curl to get the plugins installed:
```
curl localhost:8083/connector-plugins/
[{"class":"org.apache.kafka.connect.file.FileStreamSinkConnector","type":"sink","version":"5.3.1-ccs"},{"class":"org.apache.kafka.connect.file.FileStreamSourceConnector","type":"source","version":"5.3.1-ccs"}]
```

When I exec into the container, /etc/kafka-connect/kafka-connect.properties does not have plugin.path. Both /etc/kafka/connect-standalone.properties and /etc/kafka/connect-distributed.properties have plugin.path set to /usr/share/java. 

I actually found this while trying to create an image with community plugins: 
```
FROM confluentinc/cp-kafka-connect-base:5.3.1
RUN  confluent-hub install --no-prompt hpgrahsl/kafka-connect-mongodb:1.3.1 && \
     confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:0.2
```

And the plugins were not showing up, so I tried with just the base image, which should have more than the File connector installed. 

The fix is passing the plugin path as an env var when starting the container: 
-e CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

**Comment by cricket007** [comment]
I think the problem is that you're using confluentinc/cp-kafka-connect-base

Instead of confluentinc/cp-kafka-connect

**Comment by brmakana** [comment]
Thanks @cricket007  - many of the examples show using cp-kafka-connect-base, so it may help to call out using cp-kafka-connect instead.

**Comment by cricket007** [comment]
`CONNECT_PLUGIN_PATH` may already be defined in that container. 

The alternative is manually setting it, like you've pointed out.
