### ISSUE TITLE
Ubi8 images cannot set KAFKA_JMX_HOSTNAME because hostname command is missing

### ISSUE THREAD

**Issue by MrMarshall** [confluentinc/cp-docker-images#841]
The new ubi8 docker images (kafka/zookeeper version 5.4.1-1-ubi8) cannot automatically set KAFKA_JMX_HOSTNAME because the hostname command is missing.

`The exact error message:
/etc/confluent/docker/launch: line 28: hostname: command not found
===> Printing /var/lib/zookeeper/data/myid
===> Launching zookeeper ...
`

This can be fixed by running `yum -y install hostname` in the ubi8 cp-base image.

**Comment by janjwerner-confluent** [comment]
hostname command is installed in the cp-base-new container image. closing this issue.

**Comment by marcelrend** [comment]
Thanks @janjwerner-confluent
