### ISSUE TITLE
How to add a new local connector without having confluent installed ?

### ISSUE THREAD

**Issue by bcashier** [confluentinc/cp-docker-images#861]
Hi,

I am running on an independant installation:
- Launching zookeeper and Kafka broker using bitnami/images:tag

I want now to use `confluentinc/cp-kafka-connect-base:5.5.0` image to integrate a local connector that I used to launch using this command line:

```
./connect-standalone.sh ../../config/connect-standalone.properties ../../config/quickstart-mysql.properties ../../config/quickstart-mysql-sink.properties
```

I already found about this tutorial:
https://docs.confluent.io/current/connect/managing/extending.html

But it shows a Dockerfiles that depend on Confluent only.

How will I be able to use this image to add and create a connector image to use with docker-compose please ? I can't find this infos nowhere.

**Comment by ewencp** [comment]
Docker compose can build images, but you still need a Dockerfile for the build context if you aren't just using existing images. If you want to manage the entire lifecycle in docker-compose, you'd write a Dockerfile using the instructions you linked to, then use that for your `build` step in your docker-compose.

It should also be possible to do this by mounting a volume containing the connector into a docker image (`volumes` directive in docker-compose), but one way or another you need to download and install the connector.

**Comment by bcashier** [comment]
Thank you @ewencp for your answer, but cp-kafka-connect-base will still depend on it.

Do you have an example to suggest ?

Thank you

**Comment by OneCricketeer** [comment]
@bcashier Hey, I'm not sure I understand the question, but `cp-connect-base` is what you want... You can even just look at `cp-connect` as example of what you want (extending the images with other connectors). 

In fact, I have myself a Kafka Connect docker image that just builds the Apache source - https://github.com/OneCricketeer/apache-kafka-connect-docker

**Comment by bcashier** [comment]
@OneCricketeer Is it possible to launch multiple connectors using this:
https://github.com/OneCricketeer/apache-kafka-connect-docker

What is the difference between your solution and using connect-standalone.sh with multiple config files ?

Thank you again !

**Comment by OneCricketeer** [comment]
`connect-standalone` does not store data back into Kafka, therefore it is portable, recoverable, nor scalable.

My image, as well as Confluent's, use `connect-distributed`, which you could as well

https://docs.confluent.io/current/connect/concepts.html#distributed-workers

You use a the REST API to add and configure connectors, using JSON payloads rather than property files

**Comment by bcashier** [comment]
@OneCricketeer Is it safe to use multiple connectors at once using your Image ? Or it is preferably to launch each connector in her own container ?

Thank you again !

**Comment by OneCricketeer** [comment]
@bcashier My image doesn't run any differently than Confluent ones. It's the same main method.

**Comment by bcashier** [comment]
@OneCricketeer So they run simultaneously all the connectors at once in one container ?

Sorry, I don't know how confluent one working :)

Thanks again to enlighten me on this subject !

**Comment by OneCricketeer** [comment]
@bcashier Please refer to the link I provided above

**Comment by bcashier** [comment]
@OneCricketeer I will, thank you !
