### ISSUE TITLE
Missing 5.0.5 tag

### ISSUE THREAD

**Issue by roman-popenov** [confluentinc/cp-docker-images#863]
Hello,

Currently, I am want to use the latest Confluent images of the Kafka and associated Zookeeper. The latest version is 5.0.5 which supports Kafka 2.5. In order to pull the images, I either have to use the tag latest or by the digest.
Example
`image: confluentinc/cp-zookeeper@sha256:6e33666a21ed552cf4a6b9096a2fa94c954a60c17ec470a20f0422b9cbaa6a26` or `image: confluentinc/cp-zookeeper:latest`. I know that the tag `latest` tag is not recommended, but the tag `5.0.5` is not available, so I have to use the digest. As the result, the readability might be affected as the sha doesn't convey user friendly information. Is there a reason as to why the tag `5.0.5` unavailable?

**Comment by ewencp** [comment]
5.0.5 has not been released, the most recent release in the 5.0.x line is 5.0.4, which was released just a couple of weeks ago.

**Comment by roman-popenov** [comment]
Ok, so the `latest` wouldn't be stable release then I imagine?

**Comment by andrewegel** [comment]
> The latest version is 5.0.5 which supports Kafka 2.5.

This isn't correct Apache-Kafka 2.5 is shipped in the Confluent 5.5.0 versions. As @ewencp also pointed out, 5.0.5 doesn't exist (yet), for the 5.0.x line (Apache-Kafka 2.0), that release would be 5.0.4.

> @ewencp Ok, so the latest wouldn't be stable release then I imagine?

Latest will always point to the latest confluent platform release, which is 5.5.0 (today), and will be updated to 5.5.1 when its released.

**Comment by roman-popenov** [comment]
Yes, I got completely mixed up in versions and tags. Let's blame it on dyslexia, shall we? 😅
