### ISSUE TITLE
DockerHub page is returning 404

### ISSUE THREAD

**Issue by vadimostanin** [confluentinc/cp-docker-images#893]
404 page is returned on many NonOfficial images, 
I iterated through search list by keyword "linuxmint", but non of them is available,
for example "https://hub.docker.com/r/linuxmintd/mint20.1-amd64"

**Comment by andrewegel** [comment]
What does `linuxmintd` have to do with Confluent? We do not manage that Docker Hub Repo. Feel free to re-open if theres something more specific to all out.
