### ISSUE TITLE
Where is the cp-kafka-connect image document?

### ISSUE THREAD

**Issue by dailyworker** [confluentinc/cp-docker-images#899]
Currently, i want to modify the image, but we haven't found the relevant document or wiki for 3 hours. 

Could you find a document written about the dockerfile or environment of this image(`confluentinc/cp-kafka-connect`)?

**Comment by gAmUssA** [comment]
https://docs.confluent.io/platform/current/installation/docker/development.html

Hopefully this helps

**Comment by dailyworker** [comment]
@gAmUssA Thank you very much for your reply.

I have another question, does this image only work on the content cloud?

**Comment by dailyworker** [comment]
@gAmUssA Thanks!!
