### ISSUE TITLE
confluentinc/cp-kafka:latest docker doesn't work in DinD setup

### ISSUE THREAD

**Issue by myDisconnect** [confluentinc/cp-docker-images#912]
Kafka broker fails to start with an error:

> ===> User
> uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
> ===> Configuring ...
> Command [/usr/local/bin/dub path /etc/kafka/ writable] FAILED !

**Comment by andrewegel** [comment]
Duplicate https://github.com/confluentinc/kafka-images/issues/127
