### ISSUE TITLE
Determine actual Kafka version that is being used inside confluentinc/cp-kafka:6.2.2 image.

### ISSUE THREAD

**Issue by MUsman1992** [confluentinc/cp-docker-images#915]
I want to determine the exact version of Kafka inside confluentinc/cp-kafka:6.2.2 image. On this site, https://docs.confluent.io/platform/current/installation/versions-interoperability.html#cp-and-apache-ak-compatibility I have read that inside image with tag 6.2.x kafka version 2.8.x is being used but I want to determine the exact version of kafka. I want to know whether the exact version is 2.8.1 or 2.8.0. I also went inside this folder inside docker container /usr/share/java/kafka but could not determine the exact version of the kafka. The files of this folder can be viewed in the below diagram.
<img width="1280" alt="Screenshot 2022-01-24 at 19 22 56" src="https://user-images.githubusercontent.com/62036653/150841554-47b22232-a021-45e0-a6c3-cce3e32d8c20.png">
Can anyone guide me in this regard. Thanks

**Comment by OneCricketeer** [comment]
I answered a similar question on Stackoverflow

Note: This repo no longer deploys the kafka container images

**Comment by andrewegel** [comment]
There is no "exact version" mapping between apache/kafka and confluent/kafka (Confluent Community Server) except for the initial .0 release. As in CP 6.2.0 will ship with something that is very close to AK 2.8.0. After the .0 release there is no direct mapping, as confluent will put out releases on a different cadence than that of apache/kafka.

Instead you can look at the CP tags (v6.2.2) in https://github.com/confluentinc/kafka to get a rough idea of where/how that relates too apache/kafka 2.8.x
